
import { Language } from './types';

export const ACADEMY_NAME = "Muhammadi Online Academy";
export const PHONE_NUMBER = "+93 79 646 4640";

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    dir: 'ltr',
    name: 'Muhammadi Online Academy',
    shortName: 'Muhammadi Academy',
    tagline: 'Connecting Hearts with Knowledge for Every Learner',
    brighterLearning: 'Brighter Learning',
    heroSub: 'At Muhammadi Online Academy, we connect hearts with foundational knowledge across faith, character, and modern skills. We believe learning should build strong values, critical thinking, and practical capability for every learner.',
    mission: 'Guided by faith and excellence, we deliver knowledge that shapes character, builds skills, and serves communities.',
    nav: { courses: 'Courses', pricing: 'Pricing', admission: 'Admission', enroll: 'Enroll Now', login: 'Login', signUp: 'Sign Up', dashboard: 'Dashboard', logout: 'Logout', register: 'Register', explore: 'Explore Courses', exploreSubjects: 'Explore subjects', findPath: 'Find your learning path', viewAllCourses: 'View all courses', seeMore: 'See more', startLearning: 'Start Learning', knowledgeStore: 'Knowledge Store', searchPlaceholder: 'What do you want to learn? (e.g., Quran, Arabic)', quickResults: 'Quick Results for', viewAllResults: 'View all results for', courses_label: 'courses' },
    courses: {
      title: 'What We Offer',
      subtitle: 'All classes are one-to-one, interactive, and designed according to the student\'s level',
      c1: 'Qur\'an Reading with Tajweed',
      c1Desc: 'Master the rules of recitation with precision and beauty.',
      c2: 'Qur\'an Translation & Tafsir',
      c2Desc: 'Deepen your understanding of the Divine message.',
      c3: 'Noorani Qaida for Beginners',
      c3Desc: 'Foundational reading for new learners.',
      c4: 'Memorization (Hifz) with Revision',
      c4Desc: 'Systematic memorization with regular revision system.',
      c5: 'Arabic Language',
      c5Desc: 'Learn to speak and understand the language of the Qur\'an.',
      c6: 'Islamic Studies & Daily Duas',
      c6Desc: 'Comprehensive lessons on faith, manners, and daily practices.'
    },
    pricing: {
      title: 'Tuition Packages',
      subtitle: 'Simple and affordable monthly rates',
      basic: 'Basic Package',
      standard: 'Standard Package',
      premium: 'Premium Package',
      month: 'month',
      popular: 'Most Popular',
      choose: 'Choose Plan',
      register: 'Register',
      basicFeatures: ['2 Classes Per Week', '30-Minute Sessions', 'Qualified Teacher'],
      standardFeatures: ['3 Classes Per Week', '45-Minute Sessions', 'Certified Teacher', 'Progress Reports'],
      premiumFeatures: ['5 Classes Per Week', '60-Minute Sessions', 'Expert Teacher', 'Weekly Reports', 'Priority Support']
    },
    features: {
      title: 'Featured Content',
      subtitle: 'Explore our latest videos, resources, and Islamic content',
      addFeature: 'Add Feature',
      editFeature: 'Edit Feature',
      deleteFeature: 'Delete Feature',
      featureTitle: 'Feature Title',
      featureDescription: 'Feature Description',
      featureType: 'Content Type',
      video: 'Video',
      image: 'Image',
      text: 'Text',
      uploadMedia: 'Upload Media',
      mediaUrl: 'Media URL',
      publishDate: 'Publish Date',
      noFeatures: 'No features available yet',
      viewMore: 'View More'
    },
    form: {
      title: 'Registration Form',
      notice: 'Classes are conducted with male and female teachers separately according to Islamic guidelines.',
      studentName: 'Student Name',
      age: 'Student Age',
      parentName: 'Parent Name',
      phone: 'Phone / WhatsApp',
      selectCourse: 'Select Program',
      schedule: 'Time Preference',
      morning: 'Morning',
      evening: 'Evening',
      submit: 'Submit Registration',
      success: 'JazakAllah! Request Received.',
      successSub: 'Our support team will contact you shortly.',
      gender: 'Student Gender',
      male: 'Male',
      female: 'Female',
      preferredTeacher: 'Preferred Teacher Gender',
      maleTeacher: 'Male Teacher',
      femaleTeacher: 'Female Teacher',
      noPreference: 'No Preference',
      studentAgeLabel: 'Age',
      country: 'Country',
      timezone: 'Time Zone',
      quranLevel: 'Level of Qur\'an',
      beginner: 'Beginner (cannot read)',
      canRead: 'Can read but not tajweed',
      tajweedLevel: 'Tajweed level',
      hifzStudent: 'Hifz student',
      availability: 'Availability',
      availableDays: 'Select Available Days',
      preferredTime: 'Preferred Time',
      parentSection: 'Parent Information (for minors)',
      parentEmail: 'Parent Email',
      ourCourses: 'Our Courses',
      comprehensiveEducation: 'Comprehensive Islamic education from qualified teachers',
      filterBy: 'Filter by',
      allCourses: 'All Courses',
      allLevels: 'All Levels',
      intermediate: 'Intermediate',
      advanced: 'Advanced',
      viewDetails: 'View Details'
    },
    articles: {
      title: 'Islamic Articles & Reflections',
      heading: 'Discover Wisdom & Guidance',
      subtitle: 'Authentic Islamic content connecting real-life events and daily struggles with the eternal wisdom of the Qur\'an and Sunnah.',
      readArticle: 'Read Article',
      readTime: 'min read',
      category: 'Knowledge & Learning',
      audience: 'Mixed Audience',
      joinCommunity: 'Join Our Learning Community',
      joinText: 'Enroll in our courses to deepen your understanding of Islam and connect with knowledge seekers worldwide.',
      backToArticles: 'Back to Articles'
    },
    aboutUs: {
      title: 'About Us',
      subtitle: 'Empowering Muslims worldwide to connect with the Holy Quran through accessible, high-quality online education with dedicated teachers.',
      ourMission: 'Our Mission',
      missionText: 'To provide authentic Quranic education that transforms lives by building strong foundations in faith, character, and knowledge.',
      ourVision: 'Our Vision',
      visionText: 'A world where every Muslim has access to quality Islamic education, fostering a generation committed to the Qur\'an and Sunnah.',
      whyChooseUs: 'Why Choose Us',
      qualifiedTeachers: 'Qualified Teachers',
      qualifiedTeachersDesc: 'Certified instructors with Ijazah in Quranic recitation and years of teaching experience.',
      flexibleSchedule: 'Flexible Schedule',
      flexibleScheduleDesc: 'Learn at your own pace with class timings that fit your lifestyle.',
      oneOnOne: 'One-on-One Classes',
      oneOnOneDesc: 'Personalized attention with individual sessions tailored to your learning needs.',
      islamicEnvironment: 'Islamic Environment',
      islamicEnvironmentDesc: 'Gender-separated classes following Islamic guidelines with parental monitoring.',
      affordableFees: 'Affordable Fees',
      affordableFeesDesc: 'Quality education at reasonable prices with flexible payment plans.',
      provenResults: 'Proven Results',
      provenResultsDesc: 'Thousands of students have successfully completed their Quranic journey with us.'
    },
    dashboard: {
      admin: {
        title: 'Admin Panel',
        dashboard: 'Dashboard',
        courses: 'Courses',
        createCourse: 'Create Course',
        editCourses: 'Edit Courses',
        lessonsManager: 'Lessons Manager',
        mediaLibrary: 'Media Library',
        students: 'Students',
        addStudent: 'Add Student',
        allStudents: 'All Students',
        progressRecords: 'Progress Records',
        admissions: 'Admissions',
        teachers: 'Teachers',
        addTeacher: 'Add Teacher',
        teacherList: 'Teacher List',
        schedule: 'Schedule',
        academic: 'Academic',
        attendance: 'Attendance',
        homework: 'Homework',
        exams: 'Exams & Quizzes',
        results: 'Results',
        finance: 'Finance',
        feeRecords: 'Fee Records',
        feePlans: 'Fee Plans',
        invoices: 'Invoices',
        payments: 'Payments',
        reports: 'Reports',
        communication: 'Communication',
        announcements: 'Announcements',
        messages: 'Messages',
        website: 'Website CMS',
        homePage: 'Home Page',
        pricingPackages: 'Pricing Packages',
        coursesPage: 'Courses Page',
        mediaBanners: 'Media & Banners',
        settings: 'Settings',
        systemSettings: 'System Settings',
        adminManagement: 'Admin Management',
        seedDatabase: 'Seed Database',
        logout: 'Logout'
      },
      teacher: {
        title: 'Teacher Portal',
        dashboard: 'Dashboard',
        myStudents: 'My Students',
        lessons: 'Lessons',
        attendance: 'Attendance',
        announcements: 'Announcements',
        logout: 'Logout'
      },
      student: {
        title: 'Student Portal',
        dashboard: 'Dashboard',
        myProgress: 'My Progress',
        myProfile: 'My Profile',
        attendance: 'Attendance',
        fees: 'Fees',
        announcements: 'Announcements',
        logout: 'Logout'
      },
      common: {
        welcome: 'Welcome',
        profile: 'Profile',
        notifications: 'Notifications',
        search: 'Search',
        filter: 'Filter',
        export: 'Export',
        import: 'Import',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        view: 'View',
        add: 'Add',
        submit: 'Submit',
        close: 'Close',
        confirm: 'Confirm',
        loading: 'Loading...',
        noData: 'No data available',
        error: 'Error',
        success: 'Success',
        warning: 'Warning',
        info: 'Information',
        contact: 'Contact Us'
      }
    },
    chat: {
      greeting: 'Salam Alaikum! Welcome to Mohammadi Academy. How can we assist you today?',
      placeholder: 'Ask a question...',
      support: 'Academy Support'
    },
    faq: {
      title: 'Frequently Asked Questions',
      subtitle: 'Find answers to common questions about our academy',
      ctaTitle: 'Still have questions?',
      ctaText: 'Our support team is here to help. Reach out to us anytime!',
      ctaButton: 'Contact Us',
      items: [
        {
          question: 'How do I enroll in a course?',
          answer: 'You can enroll through our website by clicking the "Admission" button on the homepage. Fill out the registration form with your details, and our team will contact you to confirm your enrollment and discuss the best course options for your level.'
        },
        {
          question: 'What are your class timings?',
          answer: 'We offer flexible scheduling with both morning and evening classes. You can select your preferred time slot during registration. Classes are typically 30-60 minutes long, held 2-3 times per week based on the course.'
        },
        {
          question: 'Do you offer one-on-one sessions?',
          answer: 'Yes! We offer personalized one-on-one classes tailored to your specific needs and learning pace. One-on-one sessions are ideal for accelerated learning or catching up.'
        },
        {
          question: 'Are male and female students in separate classes?',
          answer: 'Yes, we follow Islamic guidelines and maintain gender-separated classes with appropriately matched teachers. This creates a comfortable learning environment for all our students.'
        },
        {
          question: 'What if I miss a class?',
          answer: 'We understand that life happens. Missed classes can usually be made up by scheduling a makeup session with your teacher. Please notify us as soon as possible if you\'ll be absent.'
        },
        {
          question: 'What payment methods do you accept?',
          answer: 'We accept bank transfers, credit/debit cards, and digital payment platforms. Flexible payment plans are available for monthly, quarterly, and annual subscriptions.'
        },
        {
          question: 'Do you provide certificates upon completion?',
          answer: 'Yes! Upon completing a course successfully, we provide certificates recognizing your achievements. Certificates include your level of proficiency and areas of specialization.'
        },
        {
          question: 'Can I take multiple courses simultaneously?',
          answer: 'Absolutely! Many students take multiple courses to expand their knowledge. We can help you create a personalized learning schedule that works for your availability.'
        },
        {
          question: 'What equipment do I need for online classes?',
          answer: 'You\'ll need a computer, tablet, or smartphone with internet access. We recommend a quiet space for better focus. A microphone and camera are helpful for interactive classes.'
        },
        {
          question: 'How can I monitor my child\'s progress?',
          answer: 'Parents have access to a dedicated parent portal where they can track their child\'s attendance, progress, and performance. Regular progress reports are also provided.'
        },
        {
          question: 'What if I want to upgrade my course level?',
          answer: 'You can upgrade to a higher level at any time. Simply contact our support team, and we\'ll help transition you smoothly to the appropriate course level.'
        },
        {
          question: 'Do you offer trial classes?',
          answer: 'Yes! We offer free trial classes so you can experience our teaching style and meet your instructor before committing. Contact us to schedule your trial lesson.'
        }
      ]
    },
    social: {
      title: 'Follow Us',
      connect: 'Connect with us on social media'
    },
    footer: {
      explore: 'Explore',
      programs: 'Programs',
      tuition: 'Tuition',
      enrollment: 'Enrollment',
      portal: 'Portal',
      teacherLogin: 'Teacher Login',
      studentLogin: 'Student Login',
      studyGuide: 'Study Guide',
      directContact: 'Direct Contact',
      whatsappInquiry: 'WhatsApp Inquiry'
    },
    testimonials: {
      title: 'What Our Students Say',
      subtitle: 'Real success stories from our learning community',
      items: [
        {
          name: 'Fatima Ahmed',
          role: 'Student, Age 12',
          image: 'F',
          rating: 5,
          text: 'I have learned so much from the qualified teachers. The one-on-one classes help me understand Tajweed rules better. Alhamdulillah, I completed my first Quran recitation with proper Tajweed!'
        },
        {
          name: 'Muhammad Hassan',
          role: 'Parent',
          image: 'M',
          rating: 5,
          text: 'My son\'s progress has been remarkable. The teachers are very dedicated and patient. The flexible schedule works perfectly for our family. Highly recommended for anyone seeking quality Quranic education.'
        },
        {
          name: 'Aisha Khan',
          role: 'Student, Age 9',
          image: 'A',
          rating: 5,
          text: 'I love my teacher! She makes learning fun and easy. I can read the Quran now and understand what I am reading. The class schedule fits my school timing perfectly!'
        },
        {
          name: 'Omar Ibrahim',
          role: 'Working Professional',
          image: 'O',
          rating: 5,
          text: 'As someone with a busy schedule, the flexible timing was a game-changer. The one-on-one sessions allowed me to learn at my own pace. Best investment in my Islamic education!'
        },
        {
          name: 'Layla Rahman',
          role: 'Parent',
          image: 'L',
          rating: 5,
          text: 'The gender-separated classes align with our family values. My daughter feels comfortable and is making excellent progress. The teachers communicate regularly about her advancement.'
        }
      ]
    },
    quran: {
      title: 'Al-Qur\'an Companion',
      surah: 'Surah',
      ayah: 'Ayah',
      juz: 'Juz',
      page: 'Page',
      search: 'Search',
      bookmarks: 'Bookmarks',
      translation: 'Translation',
      tafsir: 'Tafsir',
      audio: 'Audio',
      wordByWord: 'Word by Word',
      memorization: 'Memorization',
      readingMode: 'Reading Mode',
      settings: 'Settings',
      selectSurah: 'Select Surah',
      selectTranslation: 'Select Translation',
      play: 'Play',
      pause: 'Pause',
      repeat: 'Repeat',
      previous: 'Previous',
      next: 'Next',
      addBookmark: 'Add Bookmark',
      addNote: 'Add Note',
      daily: 'Daily Ayah',
      topics: 'Topics',
      meccan: 'Meccan',
      medinan: 'Medinan',
      verses: 'Verses',
      loading: 'Loading...',
      noResults: 'No results found',
      reciter: 'Reciter',
      transliteration: 'Transliteration',
      root: 'Root',
      meaning: 'Meaning',
      grammar: 'Grammar'
    },
    studentProgress: {
      title: 'Your Progress',
      subtitle: 'Track your Quranic learning journey',
      stats: {
        overall: 'Overall Progress',
        lessons: 'Lessons',
        lessonsDesc: 'Completed',
        quizzes: 'Quizzes Passed',
        avg: 'avg',
        attendance: 'Attendance',
        attendanceDesc: 'This month'
      },
      courseProgress: 'Course Progress',
      learningDistribution: 'Learning Distribution',
      categories: ['Videos', 'Practice', 'Reading', 'Quizzes'],
      attendanceTrend: 'Attendance Trend',
      quizPerformance: 'Quiz Performance',
      quizzes: ['Quiz 1', 'Quiz 2', 'Quiz 3', 'Quiz 4', 'Quiz 5'],
      courses: ['Tajweed', 'Quran Memorization', 'Islamic Studies'],
      recentActivity: 'Recent Activity',
      today: 'Today',
      yesterday: 'Yesterday'
    },
    adminAnalytics: {
      title: 'System Analytics',
      subtitle: 'Comprehensive overview of academy performance',
      thisMonth: 'this month',
      stats: {
        students: 'Total Students',
        courses: 'Active Courses',
        revenue: 'Monthly Revenue',
        completion: 'Completion Rate'
      },
      revenueTrend: 'Revenue Trend',
      studentGrowth: 'Student Enrollment Growth',
      topCourses: 'Top Courses',
      distribution: 'Student Distribution by Level',
      retention: 'Cohort Retention',
      teacherPerformance: 'Top Teachers by Rating',
      levels: ['Beginner', 'Intermediate', 'Advanced'],
      teachers: ['Ustadha Fatima', 'Sheikh Muhammad', 'Ustadha Aisha', 'Sheikh Omar', 'Ustadha Layla'],
      courses: ['Tajweed', 'Hifz', 'Islamic Studies', 'Arabic Grammar', 'Tafsir'],
      summary: 'System Summary',
      activeStudents: 'Active Students',
      totalTeachers: 'Active Teachers',
      totalEnrollments: 'Total Enrollments',
      totalRevenue: 'Total Revenue',
      enrolled: 'of total',
      available: 'available',
      perStudent: 'per student',
      allTime: 'All time',
      students: 'students'
    },
    socialMedia: {
      title: 'Follow Us',
      subtitle: 'Connect with us on social media',
      facebook: 'Facebook',
      twitter: 'Twitter',
      instagram: 'Instagram',
      linkedin: 'LinkedIn',
      youtube: 'YouTube',
      whatsapp: 'WhatsApp',
      telegram: 'Telegram',
      tiktok: 'TikTok',
      visitPage: 'Visit Page'
    },
    exploreCategories: {
      quran: 'Quran & Tajweed',
      islamicStudies: 'Islamic Studies',
      languages: 'Languages',
      ai: 'Artificial Intelligence',
      it: 'Information Technology',
      science: 'Science',
      generalKnowledge: 'General Knowledge',
      lifeSkills: 'Life Skills',
      digitalSkills: 'Digital Skills'
    },
    studentJourney: {
      label: 'Student Journey',
      title: 'A clear roadmap from first letters to certification',
      subtitle: 'Parents and students always know what comes next, how progress is measured, and when certification is earned.',
      steps: ['Beginner Foundations', 'Tajweed Mastery', 'Memorization Track', 'Tafsir & Meaning', 'Certification'],
      levels: [
        { label: 'Beginner', detail: 'Arabic letters, reading fluency' },
        { label: 'Intermediate', detail: 'Tajweed rules and practice' },
        { label: 'Advanced', detail: 'Memorization + Tafsir skills' }
      ],
      progressTracking: 'Progress Tracking',
      liveDashboard: 'Live dashboard for parents and students',
      liveDashboardDesc: 'Attendance, teacher feedback, memorization milestones, and monthly reports in one place.',
      certification: 'Certification',
      earnCertificates: 'Earn verified certificates',
      earnCertificatesDesc: 'Students receive certificates at key milestones and final completion.',
      startJourney: 'Start Journey'
    },
    noorani: {
      badge: 'NEW COURSE',
      title1: 'Master Quran & Prayer',
      title2: 'with Noorani Qaida',
      description: 'A comprehensive 3-section course with 19 interactive lessons, quizzes, and gamification. Perfect for beginners and advancing learners.',
      feature1Title: 'Arabic Alphabet & Tajweed (12 lessons)',
      feature1Desc: 'Learn Arabic letters, Quranic rules, and perfect recitation',
      feature2Title: 'Daily Prayer (Salah) Practice (7 lessons)',
      feature2Desc: 'Complete guide with video demonstrations and step-by-step instructions',
      feature3Title: 'Progress Tracking & Certificates',
      feature3Desc: 'Earn badges, maintain streaks, and get certified upon completion',
      exploreCourse: 'Explore Course',
      lessonsCount: '19 Lessons',
      completeEducation: 'Complete Islamic Education',
      sections: 'Sections',
      lessons: 'Lessons',
      free: 'Free'
    },
    footerExtra: {
      aboutUs: 'About Us',
      aboutDesc: 'Excellence in Quranic education for all ages',
      quickLinks: 'Quick Links',
      parentDashboard: 'Parent Dashboard',
      quranLink: 'Quran',
      contactUs: 'Contact Us',
      allRights: 'All rights reserved.'
    },
    charity: {
      title: 'Mohammadi Foundation',
      subtitle: 'Supporting Islamic Education Worldwide',
      mission: 'Our Mission',
      missionText: 'To provide accessible Quranic education and Islamic knowledge to underprivileged communities across the globe.',
      impact: 'Our Impact',
      students: 'Students Supported',
      teachers: 'Teachers Trained',
      communities: 'Communities Reached',
      scholarships: 'Scholarships Given',
      donate: 'Make a Donation',
      donateNow: 'Donate Now',
      programs: 'Our Programs',
      scholarship: 'Scholarship Program',
      scholarshipDesc: 'Financial aid for deserving students who cannot afford education',
      community: 'Community Outreach',
      communityDesc: 'Free Quranic classes in underserved communities',
      teacher: 'Teacher Training',
      teacherDesc: 'Professional development programs for Islamic educators',
      research: 'Research & Development',
      researchDesc: 'Developing innovative Islamic education methodologies',
      ways: 'Ways to Donate',
      bank: 'Bank Transfer',
      card: 'Credit/Debit Card',
      mobile: 'Mobile Payment',
      crypto: 'Cryptocurrency',
      zakat: 'Zakat Eligible',
      tax: 'Tax Deductible',
      monthly: 'Become a Monthly Donor',
      monthlyDesc: 'Contribute regularly to sustained impact',
      contactDonor: 'Contact for Donations',
      email: 'Email',
      phone: 'Phone',
      thank: 'Thank You',
      thankYouMsg: 'Your generous donation makes a real difference in peoples lives'
    }
  },

  // ─── ARABIC ───────────────────────────────────────
  ar: {
    dir: 'rtl',
    name: 'أكاديمية المحمدي الإلكترونية',
    shortName: 'أكاديمية المحمدي',
    tagline: 'نربط القلوب بالمعرفة لكل متعلم',
    brighterLearning: 'تعليم أفضل',
    heroSub: 'في أكاديمية المحمدي الإلكترونية، نربط القلوب بالمعرفة الأساسية عبر الإيمان والأخلاق والمهارات الحديثة. نؤمن بأن التعليم يجب أن يبني قيماً قوية وتفكيراً نقدياً وقدرة عملية لكل متعلم.',
    mission: 'بهداية الإيمان والتميز، نقدم المعرفة التي تصقل الشخصية وتبني المهارات وتخدم المجتمعات.',
    nav: { courses: 'الدورات', pricing: 'الأسعار', admission: 'القبول', enroll: 'سجل الآن', login: 'تسجيل الدخول', signUp: 'إنشاء حساب', dashboard: 'لوحة التحكم', logout: 'تسجيل الخروج', register: 'التسجيل', explore: 'استكشاف الدورات', exploreSubjects: 'استكشف المواد', findPath: 'ابحث عن مسارك التعليمي', viewAllCourses: 'عرض جميع الدورات', seeMore: 'المزيد', startLearning: 'ابدأ التعلم', knowledgeStore: 'متجر المعرفة', searchPlaceholder: 'ماذا تريد أن تتعلم؟ (مثل: القرآن، العربية)', quickResults: 'نتائج سريعة لـ', viewAllResults: 'عرض جميع النتائج لـ', courses_label: 'دورات' },
    courses: {
      title: 'ما نقدمه',
      subtitle: 'جميع الفصول فردية وتفاعلية ومصممة حسب مستوى الطالب',
      c1: 'قراءة القرآن بالتجويد',
      c1Desc: 'أتقن قواعد التلاوة بدقة وجمال.',
      c2: 'ترجمة القرآن والتفسير',
      c2Desc: 'عمّق فهمك للرسالة الإلهية.',
      c3: 'القاعدة النورانية للمبتدئين',
      c3Desc: 'القراءة التأسيسية للمتعلمين الجدد.',
      c4: 'الحفظ مع المراجعة',
      c4Desc: 'حفظ منهجي مع نظام مراجعة منتظم.',
      c5: 'اللغة العربية',
      c5Desc: 'تعلم التحدث وفهم لغة القرآن.',
      c6: 'الدراسات الإسلامية والأدعية اليومية',
      c6Desc: 'دروس شاملة في الإيمان والآداب والممارسات اليومية.'
    },
    pricing: {
      title: 'باقات الرسوم الدراسية',
      subtitle: 'أسعار شهرية بسيطة ومعقولة',
      basic: 'الباقة الأساسية',
      standard: 'الباقة القياسية',
      premium: 'الباقة المميزة',
      month: 'شهر',
      popular: 'الأكثر شعبية',
      choose: 'اختر الخطة',
      register: 'التسجيل',
      basicFeatures: ['حصتان في الأسبوع', 'جلسات 30 دقيقة', 'معلم مؤهل'],
      standardFeatures: ['3 حصص في الأسبوع', 'جلسات 45 دقيقة', 'معلم معتمد', 'تقارير التقدم'],
      premiumFeatures: ['5 حصص في الأسبوع', 'جلسات 60 دقيقة', 'معلم خبير', 'تقارير أسبوعية', 'دعم ذو أولوية']
    },
    features: {
      title: 'المحتوى المميز',
      subtitle: 'استكشف أحدث مقاطع الفيديو والموارد والمحتوى الإسلامي',
      addFeature: 'إضافة ميزة',
      editFeature: 'تعديل ميزة',
      deleteFeature: 'حذف ميزة',
      featureTitle: 'عنوان الميزة',
      featureDescription: 'وصف الميزة',
      featureType: 'نوع المحتوى',
      video: 'فيديو',
      image: 'صورة',
      text: 'نص',
      uploadMedia: 'رفع وسائط',
      mediaUrl: 'رابط الوسائط',
      publishDate: 'تاريخ النشر',
      noFeatures: 'لا توجد ميزات بعد',
      viewMore: 'عرض المزيد'
    },
    form: {
      title: 'نموذج التسجيل',
      notice: 'تُقام الفصول مع معلمين ومعلمات بشكل منفصل وفقاً للإرشادات الإسلامية.',
      studentName: 'اسم الطالب',
      age: 'عمر الطالب',
      parentName: 'اسم ولي الأمر',
      phone: 'الهاتف / واتساب',
      selectCourse: 'اختر البرنامج',
      schedule: 'تفضيل الوقت',
      morning: 'صباحاً',
      evening: 'مساءً',
      submit: 'إرسال التسجيل',
      success: 'جزاك الله خيراً! تم استلام الطلب.',
      successSub: 'سيتواصل معك فريق الدعم قريباً.',
      gender: 'جنس الطالب',
      male: 'ذكر',
      female: 'أنثى',
      preferredTeacher: 'جنس المعلم المفضل',
      maleTeacher: 'معلم',
      femaleTeacher: 'معلمة',
      noPreference: 'لا تفضيل',
      studentAgeLabel: 'العمر',
      country: 'البلد',
      timezone: 'المنطقة الزمنية',
      quranLevel: 'مستوى القرآن',
      beginner: 'مبتدئ (لا يستطيع القراءة)',
      canRead: 'يستطيع القراءة بدون تجويد',
      tajweedLevel: 'مستوى التجويد',
      hifzStudent: 'طالب حفظ',
      availability: 'الإتاحة',
      availableDays: 'اختر الأيام المتاحة',
      preferredTime: 'الوقت المفضل',
      parentSection: 'معلومات ولي الأمر (للقاصرين)',
      parentEmail: 'بريد ولي الأمر',
      ourCourses: 'دوراتنا',
      comprehensiveEducation: 'تعليم إسلامي شامل من معلمين مؤهلين',
      filterBy: 'تصفية حسب',
      allCourses: 'جميع الدورات',
      allLevels: 'جميع المستويات',
      intermediate: 'متوسط',
      advanced: 'متقدم',
      viewDetails: 'عرض التفاصيل'
    },
    articles: {
      title: 'مقالات وتأملات إسلامية',
      heading: 'اكتشف الحكمة والهداية',
      subtitle: 'محتوى إسلامي أصيل يربط أحداث الحياة والتحديات اليومية بحكمة القرآن والسنة الخالدة.',
      readArticle: 'اقرأ المقال',
      readTime: 'دقائق للقراءة',
      category: 'المعرفة والتعلم',
      audience: 'جمهور متنوع',
      joinCommunity: 'انضم إلى مجتمعنا التعليمي',
      joinText: 'سجل في دوراتنا لتعميق فهمك للإسلام والتواصل مع طلاب العلم حول العالم.',
      backToArticles: 'العودة للمقالات'
    },
    aboutUs: {
      title: 'من نحن',
      subtitle: 'تمكين المسلمين حول العالم للتواصل مع القرآن الكريم من خلال تعليم إلكتروني عالي الجودة مع معلمين متخصصين.',
      ourMission: 'رسالتنا',
      missionText: 'تقديم تعليم قرآني أصيل يغيّر الحياة من خلال بناء أسس قوية في الإيمان والشخصية والمعرفة.',
      ourVision: 'رؤيتنا',
      visionText: 'عالم يحصل فيه كل مسلم على تعليم إسلامي عالي الجودة، لتنشئة جيل ملتزم بالقرآن والسنة.',
      whyChooseUs: 'لماذا تختارنا',
      qualifiedTeachers: 'معلمون مؤهلون',
      qualifiedTeachersDesc: 'مدرسون معتمدون بإجازة في تلاوة القرآن وسنوات من الخبرة التعليمية.',
      flexibleSchedule: 'جدول مرن',
      flexibleScheduleDesc: 'تعلم بالسرعة التي تناسبك مع مواعيد تناسب نمط حياتك.',
      oneOnOne: 'فصول فردية',
      oneOnOneDesc: 'اهتمام شخصي بجلسات فردية مصممة حسب احتياجاتك التعليمية.',
      islamicEnvironment: 'بيئة إسلامية',
      islamicEnvironmentDesc: 'فصول منفصلة حسب الجنس وفق الإرشادات الإسلامية مع مراقبة أولياء الأمور.',
      affordableFees: 'رسوم معقولة',
      affordableFeesDesc: 'تعليم عالي الجودة بأسعار مناسبة مع خطط دفع مرنة.',
      provenResults: 'نتائج مثبتة',
      provenResultsDesc: 'آلاف الطلاب أكملوا رحلتهم القرآنية معنا بنجاح.'
    },
    dashboard: {
      admin: {
        title: 'لوحة الإدارة',
        dashboard: 'لوحة التحكم',
        courses: 'الدورات',
        createCourse: 'إنشاء دورة',
        editCourses: 'تعديل الدورات',
        lessonsManager: 'إدارة الدروس',
        mediaLibrary: 'مكتبة الوسائط',
        students: 'الطلاب',
        addStudent: 'إضافة طالب',
        allStudents: 'جميع الطلاب',
        progressRecords: 'سجلات التقدم',
        admissions: 'القبول',
        teachers: 'المعلمون',
        addTeacher: 'إضافة معلم',
        teacherList: 'قائمة المعلمين',
        schedule: 'الجدول',
        academic: 'الشؤون الأكاديمية',
        attendance: 'الحضور',
        homework: 'الواجبات',
        exams: 'الامتحانات والاختبارات',
        results: 'النتائج',
        finance: 'المالية',
        feeRecords: 'سجلات الرسوم',
        feePlans: 'خطط الرسوم',
        invoices: 'الفواتير',
        payments: 'المدفوعات',
        reports: 'التقارير',
        communication: 'التواصل',
        announcements: 'الإعلانات',
        messages: 'الرسائل',
        website: 'إدارة الموقع',
        homePage: 'الصفحة الرئيسية',
        pricingPackages: 'باقات الأسعار',
        coursesPage: 'صفحة الدورات',
        mediaBanners: 'الوسائط واللافتات',
        settings: 'الإعدادات',
        systemSettings: 'إعدادات النظام',
        adminManagement: 'إدارة المسؤولين',
        seedDatabase: 'تهيئة قاعدة البيانات',
        logout: 'تسجيل الخروج'
      },
      teacher: {
        title: 'بوابة المعلم',
        dashboard: 'لوحة التحكم',
        myStudents: 'طلابي',
        lessons: 'الدروس',
        attendance: 'الحضور',
        announcements: 'الإعلانات',
        logout: 'تسجيل الخروج'
      },
      student: {
        title: 'بوابة الطالب',
        dashboard: 'لوحة التحكم',
        myProgress: 'تقدمي',
        myProfile: 'ملفي الشخصي',
        attendance: 'الحضور',
        fees: 'الرسوم',
        announcements: 'الإعلانات',
        logout: 'تسجيل الخروج'
      },
      common: {
        welcome: 'مرحباً',
        profile: 'الملف الشخصي',
        notifications: 'الإشعارات',
        search: 'بحث',
        filter: 'تصفية',
        export: 'تصدير',
        import: 'استيراد',
        save: 'حفظ',
        cancel: 'إلغاء',
        delete: 'حذف',
        edit: 'تعديل',
        view: 'عرض',
        add: 'إضافة',
        submit: 'إرسال',
        close: 'إغلاق',
        confirm: 'تأكيد',
        loading: 'جاري التحميل...',
        noData: 'لا توجد بيانات',
        error: 'خطأ',
        success: 'نجاح',
        warning: 'تحذير',
        info: 'معلومات',
        contact: 'اتصل بنا'
      }
    },
    chat: {
      greeting: 'السلام عليكم! مرحباً بكم في أكاديمية المحمدي. كيف يمكننا مساعدتكم اليوم؟',
      placeholder: 'اطرح سؤالاً...',
      support: 'دعم الأكاديمية'
    },
    faq: {
      title: 'الأسئلة الشائعة',
      subtitle: 'اعثر على إجابات للأسئلة الشائعة حول أكاديميتنا',
      ctaTitle: 'لا تزال لديك أسئلة؟',
      ctaText: 'فريق الدعم لدينا هنا للمساعدة. تواصل معنا في أي وقت!',
      ctaButton: 'اتصل بنا',
      items: [
        {
          question: 'كيف أسجل في دورة؟',
          answer: 'يمكنك التسجيل عبر موقعنا بالنقر على زر "القبول" في الصفحة الرئيسية. املأ نموذج التسجيل بمعلوماتك وسيتواصل معك فريقنا لتأكيد التسجيل ومناقشة أفضل خيارات الدورات لمستواك.'
        },
        {
          question: 'ما هي مواعيد الفصول؟',
          answer: 'نقدم جدولاً مرناً مع فصول صباحية ومسائية. يمكنك اختيار الوقت المفضل لديك أثناء التسجيل. عادة ما تكون الفصول من 30 إلى 60 دقيقة، وتُعقد 2-3 مرات في الأسبوع حسب الدورة.'
        },
        {
          question: 'هل تقدمون جلسات فردية؟',
          answer: 'نعم! نقدم فصولاً فردية مخصصة وفقاً لاحتياجاتك وسرعة تعلمك. الجلسات الفردية مثالية للتعلم المتسارع أو اللحاق بالركب.'
        },
        {
          question: 'هل الطلاب والطالبات في فصول منفصلة؟',
          answer: 'نعم، نتبع الإرشادات الإسلامية ونحافظ على فصول منفصلة حسب الجنس مع معلمين مناسبين. هذا يخلق بيئة تعليمية مريحة لجميع طلابنا.'
        },
        {
          question: 'ماذا لو فاتني فصل؟',
          answer: 'نحن نتفهم أن الحياة مليئة بالمشاغل. يمكن عادةً تعويض الفصول الفائتة بجدولة جلسة تعويضية مع معلمك. يرجى إبلاغنا في أقرب وقت ممكن إذا كنت ستتغيب.'
        },
        {
          question: 'ما طرق الدفع المقبولة؟',
          answer: 'نقبل التحويلات البنكية وبطاقات الائتمان/الخصم ومنصات الدفع الرقمي. تتوفر خطط دفع مرنة للاشتراكات الشهرية والفصلية والسنوية.'
        },
        {
          question: 'هل تقدمون شهادات عند الإتمام؟',
          answer: 'نعم! عند إكمال الدورة بنجاح، نقدم شهادات تقدر إنجازاتك. تتضمن الشهادات مستوى كفاءتك ومجالات تخصصك.'
        },
        {
          question: 'هل يمكنني أخذ عدة دورات في آن واحد؟',
          answer: 'بالتأكيد! كثير من الطلاب يأخذون عدة دورات لتوسيع معارفهم. يمكننا مساعدتك في إنشاء جدول تعليمي مخصص يناسب وقتك.'
        },
        {
          question: 'ما المعدات المطلوبة للفصول الإلكترونية؟',
          answer: 'تحتاج إلى حاسوب أو جهاز لوحي أو هاتف ذكي مع اتصال بالإنترنت. ننصح بمكان هادئ للتركيز بشكل أفضل. الميكروفون والكاميرا مفيدان للفصول التفاعلية.'
        },
        {
          question: 'كيف يمكنني متابعة تقدم طفلي؟',
          answer: 'يحصل أولياء الأمور على وصول إلى بوابة خاصة حيث يمكنهم متابعة حضور طفلهم وتقدمه وأدائه. كما تُقدم تقارير تقدم دورية.'
        },
        {
          question: 'ماذا لو أردت ترقية مستوى دورتي؟',
          answer: 'يمكنك الترقية إلى مستوى أعلى في أي وقت. فقط تواصل مع فريق الدعم وسنساعدك في الانتقال بسلاسة إلى المستوى المناسب.'
        },
        {
          question: 'هل تقدمون فصولاً تجريبية؟',
          answer: 'نعم! نقدم فصولاً تجريبية مجانية حتى تتمكن من تجربة أسلوب التدريس ولقاء معلمك قبل الالتزام. تواصل معنا لجدولة درسك التجريبي.'
        }
      ]
    },
    social: {
      title: 'تابعونا',
      connect: 'تواصل معنا على وسائل التواصل الاجتماعي'
    },
    footer: {
      explore: 'استكشف',
      programs: 'البرامج',
      tuition: 'الرسوم الدراسية',
      enrollment: 'التسجيل',
      portal: 'البوابة',
      teacherLogin: 'دخول المعلم',
      studentLogin: 'دخول الطالب',
      studyGuide: 'دليل الدراسة',
      directContact: 'اتصال مباشر',
      whatsappInquiry: 'استفسار واتساب'
    },
    testimonials: {
      title: 'ماذا يقول طلابنا',
      subtitle: 'قصص نجاح حقيقية من مجتمعنا التعليمي',
      items: [
        {
          name: 'فاطمة أحمد',
          role: 'طالبة، 12 سنة',
          image: 'F',
          rating: 5,
          text: 'تعلمت الكثير من المعلمين المؤهلين. الفصول الفردية ساعدتني في فهم قواعد التجويد بشكل أفضل. الحمد لله، أكملت ختمتي الأولى بالتجويد الصحيح!'
        },
        {
          name: 'محمد حسن',
          role: 'ولي أمر',
          image: 'M',
          rating: 5,
          text: 'تقدم ابني كان ملحوظاً. المعلمون متفانون وصبورون جداً. الجدول المرن مناسب تماماً لعائلتنا. أوصي بشدة لكل من يبحث عن تعليم قرآني عالي الجودة.'
        },
        {
          name: 'عائشة خان',
          role: 'طالبة، 9 سنوات',
          image: 'A',
          rating: 5,
          text: 'أحب معلمتي! تجعل التعلم ممتعاً وسهلاً. أستطيع الآن قراءة القرآن وفهم ما أقرأ. جدول الفصول يتناسب مع أوقات مدرستي تماماً!'
        },
        {
          name: 'عمر إبراهيم',
          role: 'موظف',
          image: 'O',
          rating: 5,
          text: 'كشخص مشغول، المواعيد المرنة كانت نقطة تحول. الجلسات الفردية سمحت لي بالتعلم بالسرعة التي تناسبني. أفضل استثمار في تعليمي الإسلامي!'
        },
        {
          name: 'ليلى رحمن',
          role: 'ولية أمر',
          image: 'L',
          rating: 5,
          text: 'الفصول المنفصلة تتوافق مع قيم عائلتنا. ابنتي مرتاحة وتحرز تقدماً ممتازاً. المعلمون يتواصلون بانتظام حول تقدمها.'
        }
      ]
    },
    quran: {
      title: 'رفيق القرآن الكريم',
      surah: 'سورة',
      ayah: 'آية',
      juz: 'جزء',
      page: 'صفحة',
      search: 'بحث',
      bookmarks: 'العلامات المرجعية',
      translation: 'الترجمة',
      tafsir: 'التفسير',
      audio: 'صوت',
      wordByWord: 'كلمة بكلمة',
      memorization: 'الحفظ',
      readingMode: 'وضع القراءة',
      settings: 'الإعدادات',
      selectSurah: 'اختر السورة',
      selectTranslation: 'اختر الترجمة',
      play: 'تشغيل',
      pause: 'إيقاف',
      repeat: 'تكرار',
      previous: 'السابق',
      next: 'التالي',
      addBookmark: 'إضافة علامة',
      addNote: 'إضافة ملاحظة',
      daily: 'آية اليوم',
      topics: 'المواضيع',
      meccan: 'مكية',
      medinan: 'مدنية',
      verses: 'آيات',
      loading: 'جاري التحميل...',
      noResults: 'لا توجد نتائج',
      reciter: 'القارئ',
      transliteration: 'النقل الحرفي',
      root: 'الجذر',
      meaning: 'المعنى',
      grammar: 'النحو'
    },
    studentProgress: {
      title: 'تقدمك',
      subtitle: 'تتبع رحلتك في تعلم القرآن',
      stats: {
        overall: 'التقدم العام',
        lessons: 'الدروس',
        lessonsDesc: 'مكتملة',
        quizzes: 'الاختبارات الناجحة',
        avg: 'المتوسط',
        attendance: 'الحضور',
        attendanceDesc: 'هذا الشهر'
      },
      courseProgress: 'تقدم الدورة',
      learningDistribution: 'توزيع التعلم',
      categories: ['فيديوهات', 'تمارين', 'قراءة', 'اختبارات'],
      attendanceTrend: 'اتجاه الحضور',
      quizPerformance: 'أداء الاختبارات',
      quizzes: ['اختبار 1', 'اختبار 2', 'اختبار 3', 'اختبار 4', 'اختبار 5'],
      courses: ['التجويد', 'حفظ القرآن', 'الدراسات الإسلامية'],
      recentActivity: 'النشاط الأخير',
      today: 'اليوم',
      yesterday: 'أمس'
    },
    adminAnalytics: {
      title: 'تحليلات النظام',
      subtitle: 'نظرة شاملة على أداء الأكاديمية',
      thisMonth: 'هذا الشهر',
      stats: {
        students: 'إجمالي الطلاب',
        courses: 'الدورات النشطة',
        revenue: 'الإيرادات الشهرية',
        completion: 'نسبة الإكمال'
      },
      revenueTrend: 'اتجاه الإيرادات',
      studentGrowth: 'نمو تسجيل الطلاب',
      topCourses: 'أفضل الدورات',
      distribution: 'توزيع الطلاب حسب المستوى',
      retention: 'الاحتفاظ بالمجموعات',
      teacherPerformance: 'أفضل المعلمين حسب التقييم',
      levels: ['مبتدئ', 'متوسط', 'متقدم'],
      teachers: ['الأستاذة فاطمة', 'الشيخ محمد', 'الأستاذة عائشة', 'الشيخ عمر', 'الأستاذة ليلى'],
      courses: ['التجويد', 'الحفظ', 'الدراسات الإسلامية', 'النحو العربي', 'التفسير'],
      summary: 'ملخص النظام',
      activeStudents: 'الطلاب النشطون',
      totalTeachers: 'المعلمون النشطون',
      totalEnrollments: 'إجمالي التسجيلات',
      totalRevenue: 'إجمالي الإيرادات',
      enrolled: 'من الإجمالي',
      available: 'متاح',
      perStudent: 'لكل طالب',
      allTime: 'كل الأوقات',
      students: 'طلاب'
    },
    socialMedia: {
      title: 'تابعونا',
      subtitle: 'تواصل معنا على وسائل التواصل الاجتماعي',
      facebook: 'فيسبوك',
      twitter: 'تويتر',
      instagram: 'إنستغرام',
      linkedin: 'لينكد إن',
      youtube: 'يوتيوب',
      whatsapp: 'واتساب',
      telegram: 'تلغرام',
      tiktok: 'تيك توك',
      visitPage: 'زيارة الصفحة'
    },
    exploreCategories: {
      quran: 'القرآن والتجويد',
      islamicStudies: 'الدراسات الإسلامية',
      languages: 'اللغات',
      ai: 'الذكاء الاصطناعي',
      it: 'تكنولوجيا المعلومات',
      science: 'العلوم',
      generalKnowledge: 'المعرفة العامة',
      lifeSkills: 'مهارات الحياة',
      digitalSkills: 'المهارات الرقمية'
    },
    studentJourney: {
      label: 'رحلة الطالب',
      title: 'خارطة طريق واضحة من الحروف الأولى إلى الشهادة',
      subtitle: 'أولياء الأمور والطلاب يعرفون دائماً ما سيأتي بعد ذلك، وكيف يُقاس التقدم، ومتى تُمنح الشهادة.',
      steps: ['الأسس للمبتدئين', 'إتقان التجويد', 'مسار الحفظ', 'التفسير والمعنى', 'الشهادة'],
      levels: [
        { label: 'مبتدئ', detail: 'الحروف العربية، طلاقة القراءة' },
        { label: 'متوسط', detail: 'قواعد التجويد والممارسة' },
        { label: 'متقدم', detail: 'الحفظ + مهارات التفسير' }
      ],
      progressTracking: 'تتبع التقدم',
      liveDashboard: 'لوحة تحكم مباشرة للآباء والطلاب',
      liveDashboardDesc: 'الحضور وملاحظات المعلم ومعالم الحفظ والتقارير الشهرية في مكان واحد.',
      certification: 'الشهادة',
      earnCertificates: 'احصل على شهادات معتمدة',
      earnCertificatesDesc: 'يحصل الطلاب على شهادات عند المعالم الرئيسية وعند الإتمام النهائي.',
      startJourney: 'ابدأ الرحلة'
    },
    noorani: {
      badge: 'دورة جديدة',
      title1: 'أتقن القرآن والصلاة',
      title2: 'مع القاعدة النورانية',
      description: 'دورة شاملة من 3 أقسام مع 19 درساً تفاعلياً واختبارات وتحفيز. مثالية للمبتدئين والمتقدمين.',
      feature1Title: 'الأبجدية العربية والتجويد (12 درساً)',
      feature1Desc: 'تعلم الحروف العربية وقواعد القرآن والتلاوة الصحيحة',
      feature2Title: 'ممارسة الصلاة اليومية (7 دروس)',
      feature2Desc: 'دليل كامل مع عروض فيديو وتعليمات خطوة بخطوة',
      feature3Title: 'تتبع التقدم والشهادات',
      feature3Desc: 'احصل على شارات وحافظ على سلاسل الإنجاز واحصل على شهادة عند الإتمام',
      exploreCourse: 'استكشف الدورة',
      lessonsCount: '19 درساً',
      completeEducation: 'تعليم إسلامي شامل',
      sections: 'أقسام',
      lessons: 'دروس',
      free: 'مجاني'
    },
    footerExtra: {
      aboutUs: 'من نحن',
      aboutDesc: 'التميز في التعليم القرآني لجميع الأعمار',
      quickLinks: 'روابط سريعة',
      parentDashboard: 'لوحة أولياء الأمور',
      quranLink: 'القرآن',
      contactUs: 'اتصل بنا',
      allRights: 'جميع الحقوق محفوظة.'
    },
    charity: {
      title: 'مؤسسة المحمدي',
      subtitle: 'دعم التعليم الإسلامي حول العالم',
      mission: 'رسالتنا',
      missionText: 'توفير تعليم قرآني ومعرفة إسلامية للمجتمعات المحتاجة حول العالم.',
      impact: 'تأثيرنا',
      students: 'طلاب تم دعمهم',
      teachers: 'معلمون تم تدريبهم',
      communities: 'مجتمعات تم الوصول إليها',
      scholarships: 'منح دراسية مقدمة',
      donate: 'تبرع',
      donateNow: 'تبرع الآن',
      programs: 'برامجنا',
      scholarship: 'برنامج المنح الدراسية',
      scholarshipDesc: 'مساعدة مالية للطلاب المستحقين الذين لا يستطيعون تحمل تكاليف التعليم',
      community: 'التواصل المجتمعي',
      communityDesc: 'فصول قرآنية مجانية في المجتمعات المحرومة',
      teacher: 'تدريب المعلمين',
      teacherDesc: 'برامج تطوير مهني للمعلمين الإسلاميين',
      research: 'البحث والتطوير',
      researchDesc: 'تطوير منهجيات تعليمية إسلامية مبتكرة',
      ways: 'طرق التبرع',
      bank: 'تحويل بنكي',
      card: 'بطاقة ائتمان / خصم',
      mobile: 'الدفع عبر الجوال',
      crypto: 'عملات رقمية',
      zakat: 'مؤهل للزكاة',
      tax: 'معفى من الضرائب',
      monthly: 'كن متبرعاً شهرياً',
      monthlyDesc: 'ساهم بانتظام لتأثير مستدام',
      contactDonor: 'التواصل للتبرعات',
      email: 'البريد الإلكتروني',
      phone: 'الهاتف',
      thank: 'شكراً لك',
      thankYouMsg: 'تبرعك الكريم يحدث فرقاً حقيقياً في حياة الناس'
    }
  },

  // ─── FARSI ───────────────────────────────────────
  fa: {
    dir: 'rtl',
    name: 'آکادمی آنلاین محمدی',
    shortName: 'آکادمی محمدی',
    tagline: 'پیوند قلب‌ها با دانش برای هر آموزنده',
    brighterLearning: 'آموزش بهتر',
    heroSub: 'در آکادمی آنلاین محمدی، ما قلب‌ها را با دانش بنیادین در ایمان، اخلاق و مهارت‌های مدرن پیوند می‌دهیم. ما باور داریم که آموزش باید ارزش‌های قوی، تفکر انتقادی و توانایی عملی برای هر آموزنده بسازد.',
    mission: 'با هدایت ایمان و تعالی، دانشی ارائه می‌دهیم که شخصیت را شکل می‌دهد، مهارت‌ها را می‌سازد و به جوامع خدمت می‌کند.',
    nav: { courses: 'دوره‌ها', pricing: 'هزینه‌ها', admission: 'پذیرش', enroll: 'ثبت نام کنید', login: 'ورود', signUp: 'ثبت نام', dashboard: 'داشبورد', logout: 'خروج', register: 'ثبت نام', explore: 'کاوش دوره‌ها', exploreSubjects: 'کاوش موضوعات', findPath: 'مسیر یادگیری خود را بیابید', viewAllCourses: 'مشاهده همه دوره‌ها', seeMore: 'بیشتر', startLearning: 'شروع یادگیری', knowledgeStore: 'فروشگاه دانش', searchPlaceholder: 'چه می‌خواهید یاد بگیرید؟ (مثلاً قرآن، عربی)', quickResults: 'نتایج سریع برای', viewAllResults: 'مشاهده همه نتایج برای', courses_label: 'دوره' },
    courses: {
      title: 'آنچه ارائه می‌دهیم',
      subtitle: 'تمام کلاس‌ها فردی، تعاملی و متناسب با سطح دانشجو طراحی شده‌اند',
      c1: 'قرائت قرآن با تجوید',
      c1Desc: 'قوانین تلاوت را با دقت و زیبایی فرا بگیرید.',
      c2: 'ترجمه و تفسیر قرآن',
      c2Desc: 'درک خود از پیام الهی را عمیق‌تر کنید.',
      c3: 'قاعده نورانی برای مبتدیان',
      c3Desc: 'خوانش پایه برای آموزندگان جدید.',
      c4: 'حفظ قرآن با مرور',
      c4Desc: 'حفظ سیستماتیک با سیستم مرور منظم.',
      c5: 'زبان عربی',
      c5Desc: 'صحبت کردن و فهمیدن زبان قرآن را بیاموزید.',
      c6: 'مطالعات اسلامی و دعاهای روزانه',
      c6Desc: 'دروس جامع در ایمان، اخلاق و عبادات روزانه.'
    },
    pricing: {
      title: 'بسته‌های شهریه',
      subtitle: 'نرخ‌های ماهانه ساده و مقرون به صرفه',
      basic: 'بسته پایه',
      standard: 'بسته استاندارد',
      premium: 'بسته ویژه',
      month: 'ماه',
      popular: 'محبوب‌ترین',
      choose: 'انتخاب پلن',
      register: 'ثبت نام',
      basicFeatures: ['2 کلاس در هفته', 'جلسات 30 دقیقه‌ای', 'معلم واجد شرایط'],
      standardFeatures: ['3 کلاس در هفته', 'جلسات 45 دقیقه‌ای', 'معلم معتبر', 'گزارش پیشرفت'],
      premiumFeatures: ['5 کلاس در هفته', 'جلسات 60 دقیقه‌ای', 'معلم متخصص', 'گزارش‌های هفتگی', 'پشتیبانی اولویت‌دار']
    },
    features: {
      title: 'محتوای ویژه',
      subtitle: 'جدیدترین ویدیوها، منابع و محتوای اسلامی ما را کاوش کنید',
      addFeature: 'افزودن ویژگی',
      editFeature: 'ویرایش ویژگی',
      deleteFeature: 'حذف ویژگی',
      featureTitle: 'عنوان ویژگی',
      featureDescription: 'توضیح ویژگی',
      featureType: 'نوع محتوا',
      video: 'ویدیو',
      image: 'تصویر',
      text: 'متن',
      uploadMedia: 'آپلود رسانه',
      mediaUrl: 'لینک رسانه',
      publishDate: 'تاریخ انتشار',
      noFeatures: 'هنوز ویژگی‌ای موجود نیست',
      viewMore: 'مشاهده بیشتر'
    },
    form: {
      title: 'فرم ثبت نام',
      notice: 'کلاس‌ها با معلمان مرد و زن جداگانه مطابق دستورالعمل‌های اسلامی برگزار می‌شوند.',
      studentName: 'نام دانشجو',
      age: 'سن دانشجو',
      parentName: 'نام والدین',
      phone: 'تلفن / واتساپ',
      selectCourse: 'انتخاب برنامه',
      schedule: 'ترجیح زمانی',
      morning: 'صبح',
      evening: 'عصر',
      submit: 'ارسال ثبت نام',
      success: 'جزاک الله! درخواست دریافت شد.',
      successSub: 'تیم پشتیبانی ما به زودی با شما تماس خواهد گرفت.',
      gender: 'جنسیت دانشجو',
      male: 'مرد',
      female: 'زن',
      preferredTeacher: 'جنسیت معلم ترجیحی',
      maleTeacher: 'معلم مرد',
      femaleTeacher: 'معلم زن',
      noPreference: 'بدون ترجیح',
      studentAgeLabel: 'سن',
      country: 'کشور',
      timezone: 'منطقه زمانی',
      quranLevel: 'سطح قرآن',
      beginner: 'مبتدی (نمی‌تواند بخواند)',
      canRead: 'می‌تواند بخواند اما بدون تجوید',
      tajweedLevel: 'سطح تجوید',
      hifzStudent: 'دانشجوی حفظ',
      availability: 'زمان‌های آزاد',
      availableDays: 'روزهای آزاد را انتخاب کنید',
      preferredTime: 'زمان ترجیحی',
      parentSection: 'اطلاعات والدین (برای افراد زیر سن)',
      parentEmail: 'ایمیل والدین',
      ourCourses: 'دوره‌های ما',
      comprehensiveEducation: 'آموزش جامع اسلامی از معلمان واجد شرایط',
      filterBy: 'فیلتر بر اساس',
      allCourses: 'همه دوره‌ها',
      allLevels: 'همه سطوح',
      intermediate: 'متوسط',
      advanced: 'پیشرفته',
      viewDetails: 'مشاهده جزئیات'
    },
    articles: {
      title: 'مقالات و تأملات اسلامی',
      heading: 'حکمت و هدایت را کشف کنید',
      subtitle: 'محتوای اسلامی معتبر که رویدادهای واقعی زندگی و چالش‌های روزمره را با حکمت جاودان قرآن و سنت پیوند می‌دهد.',
      readArticle: 'مطالعه مقاله',
      readTime: 'دقیقه مطالعه',
      category: 'دانش و یادگیری',
      audience: 'مخاطب عمومی',
      joinCommunity: 'به جامعه آموزشی ما بپیوندید',
      joinText: 'در دوره‌های ما ثبت نام کنید تا درک خود از اسلام را عمیق‌تر کنید و با جویندگان دانش در سراسر جهان ارتباط برقرار کنید.',
      backToArticles: 'بازگشت به مقالات'
    },
    aboutUs: {
      title: 'درباره ما',
      subtitle: 'توانمندسازی مسلمانان در سراسر جهان برای ارتباط با قرآن کریم از طریق آموزش آنلاین باکیفیت با معلمان متعهد.',
      ourMission: 'مأموریت ما',
      missionText: 'ارائه آموزش قرآنی اصیل که زندگی‌ها را با ساختن پایه‌های محکم در ایمان، شخصیت و دانش متحول می‌کند.',
      ourVision: 'چشم‌انداز ما',
      visionText: 'جهانی که هر مسلمان به آموزش اسلامی باکیفیت دسترسی داشته باشد و نسلی متعهد به قرآن و سنت پرورش یابد.',
      whyChooseUs: 'چرا ما را انتخاب کنید',
      qualifiedTeachers: 'معلمان واجد شرایط',
      qualifiedTeachersDesc: 'مدرسان معتبر با اجازه در قرائت قرآن و سال‌ها تجربه تدریس.',
      flexibleSchedule: 'برنامه انعطاف‌پذیر',
      flexibleScheduleDesc: 'با سرعت خودتان یاد بگیرید با ساعات کلاسی که متناسب با سبک زندگی شماست.',
      oneOnOne: 'کلاس‌های فردی',
      oneOnOneDesc: 'توجه شخصی با جلسات فردی متناسب با نیازهای آموزشی شما.',
      islamicEnvironment: 'محیط اسلامی',
      islamicEnvironmentDesc: 'کلاس‌های جداگانه بر اساس جنسیت مطابق دستورالعمل‌های اسلامی با نظارت والدین.',
      affordableFees: 'هزینه‌های مقرون به صرفه',
      affordableFeesDesc: 'آموزش باکیفیت با قیمت‌های مناسب و برنامه‌های پرداخت انعطاف‌پذیر.',
      provenResults: 'نتایج اثبات شده',
      provenResultsDesc: 'هزاران دانشجو سفر قرآنی خود را با ما با موفقیت تکمیل کرده‌اند.'
    },
    dashboard: {
      admin: {
        title: 'پنل مدیریت',
        dashboard: 'داشبورد',
        courses: 'دوره‌ها',
        createCourse: 'ایجاد دوره',
        editCourses: 'ویرایش دوره‌ها',
        lessonsManager: 'مدیریت درس‌ها',
        mediaLibrary: 'کتابخانه رسانه',
        students: 'دانشجویان',
        addStudent: 'افزودن دانشجو',
        allStudents: 'همه دانشجویان',
        progressRecords: 'سوابق پیشرفت',
        admissions: 'پذیرش‌ها',
        teachers: 'معلمان',
        addTeacher: 'افزودن معلم',
        teacherList: 'لیست معلمان',
        schedule: 'برنامه زمانی',
        academic: 'امور آکادمیک',
        attendance: 'حضور و غیاب',
        homework: 'تکالیف',
        exams: 'امتحانات و آزمون‌ها',
        results: 'نتایج',
        finance: 'مالی',
        feeRecords: 'سوابق شهریه',
        feePlans: 'پلن‌های شهریه',
        invoices: 'فاکتورها',
        payments: 'پرداخت‌ها',
        reports: 'گزارش‌ها',
        communication: 'ارتباطات',
        announcements: 'اطلاعیه‌ها',
        messages: 'پیام‌ها',
        website: 'مدیریت وبسایت',
        homePage: 'صفحه اصلی',
        pricingPackages: 'بسته‌های قیمت',
        coursesPage: 'صفحه دوره‌ها',
        mediaBanners: 'رسانه و بنرها',
        settings: 'تنظیمات',
        systemSettings: 'تنظیمات سیستم',
        adminManagement: 'مدیریت ادمین‌ها',
        seedDatabase: 'راه‌اندازی پایگاه داده',
        logout: 'خروج'
      },
      teacher: {
        title: 'پورتال معلم',
        dashboard: 'داشبورد',
        myStudents: 'دانشجویان من',
        lessons: 'درس‌ها',
        attendance: 'حضور و غیاب',
        announcements: 'اطلاعیه‌ها',
        logout: 'خروج'
      },
      student: {
        title: 'پورتال دانشجو',
        dashboard: 'داشبورد',
        myProgress: 'پیشرفت من',
        myProfile: 'پروفایل من',
        attendance: 'حضور و غیاب',
        fees: 'شهریه',
        announcements: 'اطلاعیه‌ها',
        logout: 'خروج'
      },
      common: {
        welcome: 'خوش آمدید',
        profile: 'پروفایل',
        notifications: 'اعلان‌ها',
        search: 'جستجو',
        filter: 'فیلتر',
        export: 'خروجی',
        import: 'ورودی',
        save: 'ذخیره',
        cancel: 'لغو',
        delete: 'حذف',
        edit: 'ویرایش',
        view: 'مشاهده',
        add: 'افزودن',
        submit: 'ارسال',
        close: 'بستن',
        confirm: 'تأیید',
        loading: 'در حال بارگذاری...',
        noData: 'داده‌ای موجود نیست',
        error: 'خطا',
        success: 'موفقیت',
        warning: 'هشدار',
        info: 'اطلاعات',
        contact: 'تماس با ما'
      }
    },
    chat: {
      greeting: 'سلام علیکم! به آکادمی محمدی خوش آمدید. چگونه می‌توانیم امروز به شما کمک کنیم؟',
      placeholder: 'سوالی بپرسید...',
      support: 'پشتیبانی آکادمی'
    },
    faq: {
      title: 'سوالات متداول',
      subtitle: 'پاسخ سوالات رایج درباره آکادمی ما را بیابید',
      ctaTitle: 'هنوز سوالی دارید؟',
      ctaText: 'تیم پشتیبانی ما اینجاست تا کمک کند. هر زمانی با ما تماس بگیرید!',
      ctaButton: 'تماس با ما',
      items: [
        {
          question: 'چگونه در یک دوره ثبت نام کنم؟',
          answer: 'می‌توانید از طریق وبسایت ما با کلیک بر دکمه "پذیرش" در صفحه اصلی ثبت نام کنید. فرم ثبت نام را پر کنید و تیم ما برای تأیید ثبت نام و بررسی بهترین گزینه‌ها با شما تماس خواهد گرفت.'
        },
        {
          question: 'ساعات کلاس‌ها چگونه است؟',
          answer: 'ما برنامه انعطاف‌پذیر با کلاس‌های صبح و عصر ارائه می‌دهیم. می‌توانید زمان مورد نظر خود را هنگام ثبت نام انتخاب کنید. کلاس‌ها معمولاً 30 تا 60 دقیقه هستند و 2-3 بار در هفته برگزار می‌شوند.'
        },
        {
          question: 'آیا جلسات فردی ارائه می‌دهید؟',
          answer: 'بله! ما کلاس‌های فردی اختصاصی متناسب با نیازها و سرعت یادگیری شما ارائه می‌دهیم. جلسات فردی برای یادگیری سریع‌تر ایده‌آل هستند.'
        },
        {
          question: 'آیا دانشجویان مرد و زن در کلاس‌های جداگانه هستند؟',
          answer: 'بله، ما از دستورالعمل‌های اسلامی پیروی می‌کنیم و کلاس‌های جداگانه با معلمان مناسب حفظ می‌کنیم. این یک محیط آموزشی راحت برای همه دانشجویان ایجاد می‌کند.'
        },
        {
          question: 'اگر کلاسی را از دست بدهم چه؟',
          answer: 'ما درک می‌کنیم. کلاس‌های از دست رفته معمولاً با برنامه‌ریزی جلسه جبرانی قابل جبران هستند. لطفاً در اسرع وقت ما را از غیبت خود مطلع کنید.'
        },
        {
          question: 'چه روش‌های پرداختی می‌پذیرید؟',
          answer: 'ما حواله بانکی، کارت اعتباری/نقدی و پلتفرم‌های پرداخت دیجیتال را می‌پذیریم. برنامه‌های پرداخت انعطاف‌پذیر برای اشتراک‌های ماهانه، سه‌ماهه و سالانه موجود است.'
        },
        {
          question: 'آیا پس از اتمام گواهینامه ارائه می‌دهید؟',
          answer: 'بله! پس از تکمیل موفق دوره، گواهینامه‌هایی ارائه می‌دهیم که دستاوردهای شما را تأیید می‌کند.'
        },
        {
          question: 'آیا می‌توانم همزمان چند دوره بگذرانم؟',
          answer: 'قطعاً! بسیاری از دانشجویان چند دوره را همزمان می‌گذرانند. ما می‌توانیم برنامه آموزشی شخصی متناسب با وقت شما ایجاد کنیم.'
        },
        {
          question: 'چه تجهیزاتی برای کلاس‌های آنلاین نیاز دارم؟',
          answer: 'به کامپیوتر، تبلت یا تلفن هوشمند با دسترسی به اینترنت نیاز دارید. فضای آرام برای تمرکز بهتر توصیه می‌شود. میکروفون و دوربین برای کلاس‌های تعاملی مفید هستند.'
        },
        {
          question: 'چگونه می‌توانم پیشرفت فرزندم را پیگیری کنم؟',
          answer: 'والدین به پورتال اختصاصی دسترسی دارند که می‌توانند حضور، پیشرفت و عملکرد فرزندشان را پیگیری کنند. گزارش‌های پیشرفت دوره‌ای نیز ارائه می‌شود.'
        },
        {
          question: 'اگر بخواهم سطح دوره‌ام را ارتقا دهم چه؟',
          answer: 'می‌توانید در هر زمان به سطح بالاتر ارتقا پیدا کنید. فقط با تیم پشتیبانی تماس بگیرید و ما به شما کمک می‌کنیم.'
        },
        {
          question: 'آیا کلاس آزمایشی ارائه می‌دهید؟',
          answer: 'بله! کلاس‌های آزمایشی رایگان ارائه می‌دهیم تا بتوانید سبک تدریس ما را تجربه کنید. برای رزرو درس آزمایشی با ما تماس بگیرید.'
        }
      ]
    },
    social: {
      title: 'ما را دنبال کنید',
      connect: 'در شبکه‌های اجتماعی با ما ارتباط برقرار کنید'
    },
    footer: {
      explore: 'کاوش',
      programs: 'برنامه‌ها',
      tuition: 'شهریه',
      enrollment: 'ثبت نام',
      portal: 'پورتال',
      teacherLogin: 'ورود معلم',
      studentLogin: 'ورود دانشجو',
      studyGuide: 'راهنمای مطالعه',
      directContact: 'تماس مستقیم',
      whatsappInquiry: 'استعلام واتساپ'
    },
    testimonials: {
      title: 'دانشجویان ما چه می‌گویند',
      subtitle: 'داستان‌های موفقیت واقعی از جامعه آموزشی ما',
      items: [
        {
          name: 'فاطمه احمد',
          role: 'دانشجو، 12 ساله',
          image: 'F',
          rating: 5,
          text: 'از معلمان واجد شرایط خیلی یاد گرفته‌ام. کلاس‌های فردی به من کمک کرد قوانین تجوید را بهتر درک کنم. الحمدلله، اولین ختم قرآنم را با تجوید صحیح تکمیل کردم!'
        },
        {
          name: 'محمد حسن',
          role: 'والد',
          image: 'M',
          rating: 5,
          text: 'پیشرفت پسرم قابل توجه بوده. معلمان بسیار متعهد و صبور هستند. برنامه انعطاف‌پذیر برای خانواده ما عالی است. به شدت توصیه می‌کنم.'
        },
        {
          name: 'عایشه خان',
          role: 'دانشجو، 9 ساله',
          image: 'A',
          rating: 5,
          text: 'معلمم را خیلی دوست دارم! یادگیری را آسان و لذت‌بخش می‌کند. حالا می‌توانم قرآن بخوانم و بفهمم چه می‌خوانم!'
        },
        {
          name: 'عمر ابراهیم',
          role: 'شاغل',
          image: 'O',
          rating: 5,
          text: 'به عنوان کسی با برنامه شلوغ، ساعات انعطاف‌پذیر عالی بود. جلسات فردی به من اجازه داد با سرعت خودم یاد بگیرم. بهترین سرمایه‌گذاری در آموزش اسلامی‌ام!'
        },
        {
          name: 'لیلا رحمان',
          role: 'والد',
          image: 'L',
          rating: 5,
          text: 'کلاس‌های جداگانه با ارزش‌های خانواده ما هماهنگ است. دخترم احساس راحتی می‌کند و پیشرفت عالی دارد.'
        }
      ]
    },
    quran: {
      title: 'همراه قرآن کریم',
      surah: 'سوره',
      ayah: 'آیه',
      juz: 'جزء',
      page: 'صفحه',
      search: 'جستجو',
      bookmarks: 'نشانک‌ها',
      translation: 'ترجمه',
      tafsir: 'تفسیر',
      audio: 'صوت',
      wordByWord: 'کلمه به کلمه',
      memorization: 'حفظ',
      readingMode: 'حالت خواندن',
      settings: 'تنظیمات',
      selectSurah: 'انتخاب سوره',
      selectTranslation: 'انتخاب ترجمه',
      play: 'پخش',
      pause: 'توقف',
      repeat: 'تکرار',
      previous: 'قبلی',
      next: 'بعدی',
      addBookmark: 'افزودن نشانک',
      addNote: 'افزودن یادداشت',
      daily: 'آیه روز',
      topics: 'موضوعات',
      meccan: 'مکی',
      medinan: 'مدنی',
      verses: 'آیات',
      loading: 'در حال بارگذاری...',
      noResults: 'نتیجه‌ای یافت نشد',
      reciter: 'قاری',
      transliteration: 'آوانویسی',
      root: 'ریشه',
      meaning: 'معنی',
      grammar: 'دستور زبان'
    },
    studentProgress: {
      title: 'پیشرفت شما',
      subtitle: 'سفر یادگیری قرآنی خود را دنبال کنید',
      stats: {
        overall: 'پیشرفت کلی',
        lessons: 'درس‌ها',
        lessonsDesc: 'تکمیل شده',
        quizzes: 'آزمون‌های موفق',
        avg: 'میانگین',
        attendance: 'حضور',
        attendanceDesc: 'این ماه'
      },
      courseProgress: 'پیشرفت دوره',
      learningDistribution: 'توزیع یادگیری',
      categories: ['ویدیوها', 'تمرین', 'خواندن', 'آزمون‌ها'],
      attendanceTrend: 'روند حضور',
      quizPerformance: 'عملکرد آزمون',
      quizzes: ['آزمون 1', 'آزمون 2', 'آزمون 3', 'آزمون 4', 'آزمون 5'],
      courses: ['تجوید', 'حفظ قرآن', 'مطالعات اسلامی'],
      recentActivity: 'فعالیت اخیر',
      today: 'امروز',
      yesterday: 'دیروز'
    },
    adminAnalytics: {
      title: 'تحلیل سیستم',
      subtitle: 'نمای کلی جامع از عملکرد آکادمی',
      thisMonth: 'این ماه',
      stats: {
        students: 'کل دانشجویان',
        courses: 'دوره‌های فعال',
        revenue: 'درآمد ماهانه',
        completion: 'نرخ تکمیل'
      },
      revenueTrend: 'روند درآمد',
      studentGrowth: 'رشد ثبت نام دانشجویان',
      topCourses: 'دوره‌های برتر',
      distribution: 'توزیع دانشجویان بر اساس سطح',
      retention: 'حفظ گروهی',
      teacherPerformance: 'معلمان برتر بر اساس امتیاز',
      levels: ['مبتدی', 'متوسط', 'پیشرفته'],
      teachers: ['استاد فاطمه', 'شیخ محمد', 'استاد عایشه', 'شیخ عمر', 'استاد لیلا'],
      courses: ['تجوید', 'حفظ', 'مطالعات اسلامی', 'نحو عربی', 'تفسیر'],
      summary: 'خلاصه سیستم',
      activeStudents: 'دانشجویان فعال',
      totalTeachers: 'معلمان فعال',
      totalEnrollments: 'کل ثبت نام‌ها',
      totalRevenue: 'کل درآمد',
      enrolled: 'از کل',
      available: 'موجود',
      perStudent: 'به ازای هر دانشجو',
      allTime: 'همه زمان‌ها',
      students: 'دانشجو'
    },
    socialMedia: {
      title: 'ما را دنبال کنید',
      subtitle: 'در شبکه‌های اجتماعی با ما ارتباط برقرار کنید',
      facebook: 'فیسبوک',
      twitter: 'توییتر',
      instagram: 'اینستاگرام',
      linkedin: 'لینکدین',
      youtube: 'یوتیوب',
      whatsapp: 'واتساپ',
      telegram: 'تلگرام',
      tiktok: 'تیک‌تاک',
      visitPage: 'مشاهده صفحه'
    },
    exploreCategories: {
      quran: 'قرآن و تجوید',
      islamicStudies: 'مطالعات اسلامی',
      languages: 'زبان‌ها',
      ai: 'هوش مصنوعی',
      it: 'فناوری اطلاعات',
      science: 'علوم',
      generalKnowledge: 'دانش عمومی',
      lifeSkills: 'مهارت‌های زندگی',
      digitalSkills: 'مهارت‌های دیجیتال'
    },
    studentJourney: {
      label: 'سفر دانشجو',
      title: 'نقشه راه روشن از حروف اول تا گواهینامه',
      subtitle: 'والدین و دانشجویان همیشه می‌دانند مرحله بعدی چیست، پیشرفت چگونه سنجیده می‌شود و گواهینامه کی اعطا می‌شود.',
      steps: ['پایه‌های مبتدی', 'تسلط بر تجوید', 'مسیر حفظ', 'تفسیر و معنا', 'گواهینامه'],
      levels: [
        { label: 'مبتدی', detail: 'حروف عربی، روانی خواندن' },
        { label: 'متوسط', detail: 'قوانین تجوید و تمرین' },
        { label: 'پیشرفته', detail: 'حفظ + مهارت‌های تفسیری' }
      ],
      progressTracking: 'پیگیری پیشرفت',
      liveDashboard: 'داشبورد زنده برای والدین و دانشجویان',
      liveDashboardDesc: 'حضور، بازخورد معلم، نقاط عطف حفظ و گزارش‌های ماهانه در یک جا.',
      certification: 'گواهینامه',
      earnCertificates: 'گواهینامه‌های معتبر دریافت کنید',
      earnCertificatesDesc: 'دانشجویان در نقاط عطف کلیدی و اتمام نهایی گواهینامه دریافت می‌کنند.',
      startJourney: 'شروع سفر'
    },
    noorani: {
      badge: 'دوره جدید',
      title1: 'تسلط بر قرآن و نماز',
      title2: 'با قاعده نورانی',
      description: 'دوره جامع 3 بخشی با 19 درس تعاملی، آزمون و گیمیفیکیشن. عالی برای مبتدیان و پیشرفته‌ها.',
      feature1Title: 'الفبای عربی و تجوید (12 درس)',
      feature1Desc: 'حروف عربی، قوانین قرآنی و تلاوت صحیح را بیاموزید',
      feature2Title: 'تمرین نماز روزانه (7 درس)',
      feature2Desc: 'راهنمای کامل با نمایش ویدیویی و دستورالعمل‌های گام به گام',
      feature3Title: 'پیگیری پیشرفت و گواهینامه‌ها',
      feature3Desc: 'نشان‌ها کسب کنید، رکوردها حفظ کنید و پس از اتمام گواهینامه بگیرید',
      exploreCourse: 'کاوش دوره',
      lessonsCount: '19 درس',
      completeEducation: 'آموزش کامل اسلامی',
      sections: 'بخش‌ها',
      lessons: 'درس‌ها',
      free: 'رایگان'
    },
    footerExtra: {
      aboutUs: 'درباره ما',
      aboutDesc: 'برتری در آموزش قرآنی برای همه سنین',
      quickLinks: 'لینک‌های سریع',
      parentDashboard: 'داشبورد والدین',
      quranLink: 'قرآن',
      contactUs: 'تماس با ما',
      allRights: 'تمامی حقوق محفوظ است.'
    },
    charity: {
      title: 'بنیاد محمدی',
      subtitle: 'حمایت از آموزش اسلامی در سراسر جهان',
      mission: 'مأموریت ما',
      missionText: 'فراهم کردن آموزش قرآنی و دانش اسلامی برای جوامع محروم در سراسر جهان.',
      impact: 'تأثیر ما',
      students: 'دانشجویان حمایت شده',
      teachers: 'معلمان آموزش دیده',
      communities: 'جوامع تحت پوشش',
      scholarships: 'بورسیه‌های اعطا شده',
      donate: 'کمک مالی',
      donateNow: 'همین الان کمک کنید',
      programs: 'برنامه‌های ما',
      scholarship: 'برنامه بورسیه',
      scholarshipDesc: 'کمک مالی برای دانشجویان مستحق که توانایی پرداخت هزینه تحصیل ندارند',
      community: 'فعالیت اجتماعی',
      communityDesc: 'کلاس‌های رایگان قرآن در جوامع محروم',
      teacher: 'آموزش معلمان',
      teacherDesc: 'برنامه‌های توسعه حرفه‌ای برای مربیان اسلامی',
      research: 'تحقیق و توسعه',
      researchDesc: 'توسعه روش‌های نوآورانه آموزش اسلامی',
      ways: 'راه‌های کمک',
      bank: 'حواله بانکی',
      card: 'کارت اعتباری / نقدی',
      mobile: 'پرداخت موبایلی',
      crypto: 'ارز دیجیتال',
      zakat: 'واجد شرایط زکات',
      tax: 'معاف از مالیات',
      monthly: 'حامی ماهانه شوید',
      monthlyDesc: 'مشارکت منظم برای تأثیر پایدار',
      contactDonor: 'تماس برای کمک مالی',
      email: 'ایمیل',
      phone: 'تلفن',
      thank: 'تشکر',
      thankYouMsg: 'کمک سخاوتمندانه شما تفاوت واقعی در زندگی مردم ایجاد می‌کند'
    }
  },

  // ─── PASHTO ───────────────────────────────────────
  ps: {
    dir: 'rtl',
    name: 'د محمدي آنلاین اکاډمي',
    shortName: 'د محمدي اکاډمي',
    tagline: 'د هر زده کوونکي لپاره د زړونو د پوهې سره تړل',
    brighterLearning: 'غوره زده کړه',
    heroSub: 'د محمدي آنلاین اکاډمي کې، موږ زړونه د ایمان، اخلاقو او عصري مهارتونو په بنسټیزه پوهه سره نښلوو. موږ باور لرو چې زده کړه باید قوي ارزښتونه، انتقادي فکر او عملي وړتیا ودروي.',
    mission: 'د ایمان او برتریا په لارښوونه، موږ هغه پوهه وړاندې کوو چې شخصیت ترتیبوي، مهارتونه جوړوي او ټولنو ته خدمت کوي.',
    nav: { courses: 'کورسونه', pricing: 'فیسونه', admission: 'شمولیت', enroll: 'اوس ثبت نام وکړئ', login: 'ننوتل', signUp: 'نوی حساب', dashboard: 'ډشبورډ', logout: 'وتل', register: 'ثبت نام', explore: 'کورسونه وپلټئ', exploreSubjects: 'موضوعات وپلټئ', findPath: 'خپل د زده کړې لاره ومومئ', viewAllCourses: 'ټول کورسونه وګورئ', seeMore: 'نور وګورئ', startLearning: 'زده کړه پیل کړئ', knowledgeStore: 'د پوهې پلورنځی', searchPlaceholder: 'تاسو څه زده کول غواړئ؟ (لکه: قرآن، عربي)', quickResults: 'ګړندي پایلې د', viewAllResults: 'ټولې پایلې وګورئ د', courses_label: 'کورسونه' },
    courses: {
      title: 'موږ څه وړاندې کوو',
      subtitle: 'ټول ټولګي انفرادي، تعاملي او د زده کوونکي د سطحې مطابق ډیزاین شوي دي',
      c1: 'د تجوید سره د قرآن لوستل',
      c1Desc: 'د تلاوت قواعد په دقت او ښکلا سره زده کړئ.',
      c2: 'د قرآن ترجمه او تفسیر',
      c2Desc: 'د الهي پیغام خپله پوهه عمیقه کړئ.',
      c3: 'د پیل کوونکو لپاره نورانی قاعده',
      c3Desc: 'د نویو زده کوونکو لپاره بنسټیزه لوستنه.',
      c4: 'حفظ د مرور سره',
      c4Desc: 'سیستماتیک حفظ د منظم مرور سیستم سره.',
      c5: 'عربي ژبه',
      c5Desc: 'د قرآن ژبه خبرې کول او پوهېدل زده کړئ.',
      c6: 'اسلامي مطالعات او ورځنۍ دعاګانې',
      c6Desc: 'د ایمان، اخلاقو او ورځنیو عبادتونو جامع درسونه.'
    },
    pricing: {
      title: 'د فیس بسته‌ګانې',
      subtitle: 'ساده او ارزانه میاشتنۍ نرخونه',
      basic: 'بنسټیزه بسته',
      standard: 'معیاري بسته',
      premium: 'ممتازه بسته',
      month: 'میاشت',
      popular: 'ترټولو مشهوره',
      choose: 'پلن غوره کړئ',
      register: 'ثبت نام',
      basicFeatures: ['په اونۍ کې 2 ټولګي', '30 دقیقې ناستې', 'وړ ښوونکی'],
      standardFeatures: ['په اونۍ کې 3 ټولګي', '45 دقیقې ناستې', 'معتبر ښوونکی', 'د پرمختګ راپورونه'],
      premiumFeatures: ['په اونۍ کې 5 ټولګي', '60 دقیقې ناستې', 'متخصص ښوونکی', 'اونیزې راپورونه', 'لومړیتوب ملاتړ']
    },
    features: {
      title: 'ځانګړی محتوا',
      subtitle: 'زموږ وروستي ویډیوګانې، سرچینې او اسلامي محتوا وپلټئ',
      addFeature: 'ویژگي اضافه کړئ',
      editFeature: 'ویژگي سمون',
      deleteFeature: 'ویژگي حذف',
      featureTitle: 'د ویژگي سرلیک',
      featureDescription: 'د ویژگي توضیح',
      featureType: 'د محتوا ډول',
      video: 'ویډیو',
      image: 'عکس',
      text: 'متن',
      uploadMedia: 'رسنۍ پورته کړئ',
      mediaUrl: 'د رسنیو لینک',
      publishDate: 'د خپرولو نیټه',
      noFeatures: 'تر اوسه ویژگي نشته',
      viewMore: 'نور وګورئ'
    },
    form: {
      title: 'د ثبت نام فورم',
      notice: 'ټولګي د اسلامي لارښوونو مطابق د نارینه او ښځینه ښوونکو سره جلا ترسره کیږي.',
      studentName: 'د زده کوونکي نوم',
      age: 'د زده کوونکي عمر',
      parentName: 'د والدین نوم',
      phone: 'تلیفون / واتساپ',
      selectCourse: 'برنامه غوره کړئ',
      schedule: 'د وخت غوره توب',
      morning: 'سهار',
      evening: 'ماښام',
      submit: 'ثبت نام واستوئ',
      success: 'جزاک الله! غوښتنه ترلاسه شوه.',
      successSub: 'زموږ ملاتړ ټیم به ډېر ژر تاسو سره اړیکه ونیسي.',
      gender: 'د زده کوونکي جنسیت',
      male: 'نارینه',
      female: 'ښځینه',
      preferredTeacher: 'غوره ښوونکی جنسیت',
      maleTeacher: 'نارینه ښوونکی',
      femaleTeacher: 'ښځینه ښوونکې',
      noPreference: 'بې غوره توب',
      studentAgeLabel: 'عمر',
      country: 'هېواد',
      timezone: 'وخت سیمه',
      quranLevel: 'د قرآن سطحه',
      beginner: 'پیل کوونکی (نشي لوستلی)',
      canRead: 'لوستلی شي خو بې تجوید',
      tajweedLevel: 'د تجوید سطحه',
      hifzStudent: 'د حفظ زده کوونکی',
      availability: 'شتون',
      availableDays: 'خالي ورځې غوره کړئ',
      preferredTime: 'غوره وخت',
      parentSection: 'د والدینو معلومات (د ماشومانو لپاره)',
      parentEmail: 'د والدینو بریښنالیک',
      ourCourses: 'زموږ کورسونه',
      comprehensiveEducation: 'د وړ ښوونکو څخه جامع اسلامي تعلیم',
      filterBy: 'فلتر',
      allCourses: 'ټول کورسونه',
      allLevels: 'ټولې سطحې',
      intermediate: 'منځنۍ',
      advanced: 'پرمختللې',
      viewDetails: 'تفصیلات وګورئ'
    },
    articles: {
      title: 'اسلامي مقالې او تأملات',
      heading: 'حکمت او لارښوونه ومومئ',
      subtitle: 'معتبر اسلامي محتوا چې د واقعي ژوند پیښې او ورځنۍ ننګونې د قرآن او سنت د ابدي حکمت سره نښلوي.',
      readArticle: 'مقاله ولولئ',
      readTime: 'دقیقې لوستل',
      category: 'پوهه او زده کړه',
      audience: 'عمومي مخاطب',
      joinCommunity: 'زموږ زده کړې ټولنې ته وګډېږئ',
      joinText: 'زموږ کورسونو کې ثبت نام وکړئ ترڅو خپله اسلامي پوهه عمیقه کړئ.',
      backToArticles: 'مقالو ته بیرته'
    },
    aboutUs: {
      title: 'زموږ په اړه',
      subtitle: 'نړیوال مسلمانان د قرآن کریم سره د باکیفیته آنلاین تعلیم له لارې وصل کول.',
      ourMission: 'زموږ ماموریت',
      missionText: 'د اصیل قرآني تعلیم وړاندې کول چې ژوند بدلوي.',
      ourVision: 'زموږ لید',
      visionText: 'یوه نړۍ چې هر مسلمان باکیفیته اسلامي تعلیم ته لاسرسی ولري.',
      whyChooseUs: 'ولې موږ غوره کړئ',
      qualifiedTeachers: 'وړ ښوونکي',
      qualifiedTeachersDesc: 'د قرآن تلاوت کې اجازه لرونکي معتبر مدرسان.',
      flexibleSchedule: 'انعطاف منونکی مهال ویش',
      flexibleScheduleDesc: 'د خپل سرعت سره زده کړئ.',
      oneOnOne: 'انفرادي ټولګي',
      oneOnOneDesc: 'ستاسو د زده کړې اړتیاو مطابق شخصي پام.',
      islamicEnvironment: 'اسلامي چاپیریال',
      islamicEnvironmentDesc: 'د اسلامي لارښوونو مطابق جلا ټولګي.',
      affordableFees: 'ارزانه فیسونه',
      affordableFeesDesc: 'باکیفیته تعلیم په مناسبه بیه.',
      provenResults: 'ثابت شوي پایلې',
      provenResultsDesc: 'زرګونو زده کوونکو خپل قرآني سفر موږ سره بریالیتوب سره بشپړ کړی.'
    },
    dashboard: {
      admin: {
        title: 'اداري پینل',
        dashboard: 'ډشبورډ',
        courses: 'کورسونه',
        createCourse: 'کورس جوړ کړئ',
        editCourses: 'کورسونه سم کړئ',
        lessonsManager: 'د درسونو مدیریت',
        mediaLibrary: 'رسنیزه کتابتون',
        students: 'زده کوونکي',
        addStudent: 'زده کوونکی اضافه کړئ',
        allStudents: 'ټول زده کوونکي',
        progressRecords: 'د پرمختګ سوابق',
        admissions: 'شمولیتونه',
        teachers: 'ښوونکي',
        addTeacher: 'ښوونکی اضافه کړئ',
        teacherList: 'د ښوونکو لیست',
        schedule: 'مهال ویش',
        academic: 'اکاډمیک چارې',
        attendance: 'حاضري',
        homework: 'کورنۍ دنده',
        exams: 'ازموینې',
        results: 'پایلې',
        finance: 'مالي چارې',
        feeRecords: 'د فیس سوابق',
        feePlans: 'د فیس پلنونه',
        invoices: 'رسیدونه',
        payments: 'تادیات',
        reports: 'راپورونه',
        communication: 'اړیکې',
        announcements: 'اعلانونه',
        messages: 'پیغامونه',
        website: 'د ویبسایټ مدیریت',
        homePage: 'اصلي پاڼه',
        pricingPackages: 'د بیو بسته‌ګانې',
        coursesPage: 'د کورسونو پاڼه',
        mediaBanners: 'رسنۍ او بینرونه',
        settings: 'امستنې',
        systemSettings: 'د سیستم امستنې',
        adminManagement: 'اداري مدیریت',
        seedDatabase: 'ډیټابیس پیل کړئ',
        logout: 'وتل'
      },
      teacher: {
        title: 'د ښوونکي پورټل',
        dashboard: 'ډشبورډ',
        myStudents: 'زما زده کوونکي',
        lessons: 'درسونه',
        attendance: 'حاضري',
        announcements: 'اعلانونه',
        logout: 'وتل'
      },
      student: {
        title: 'د زده کوونکي پورټل',
        dashboard: 'ډشبورډ',
        myProgress: 'زما پرمختګ',
        myProfile: 'زما پروفایل',
        attendance: 'حاضري',
        fees: 'فیسونه',
        announcements: 'اعلانونه',
        logout: 'وتل'
      },
      common: {
        welcome: 'ښه راغلاست',
        profile: 'پروفایل',
        notifications: 'خبرتیاوې',
        search: 'لټون',
        filter: 'فلتر',
        export: 'صادرول',
        import: 'واردول',
        save: 'خوندي کول',
        cancel: 'لغوه',
        delete: 'حذف',
        edit: 'سمون',
        view: 'لید',
        add: 'اضافه',
        submit: 'لېږل',
        close: 'بندول',
        confirm: 'تایید',
        loading: 'بار کیږي...',
        noData: 'معلومات نشته',
        error: 'تېروتنه',
        success: 'بریالیتوب',
        warning: 'خبرداری',
        info: 'معلومات',
        contact: 'موږ سره اړیکه'
      }
    },
    chat: {
      greeting: 'السلام علیکم! د محمدي اکاډمي ته ښه راغلاست. نن موږ تاسو سره څنګه مرسته کولی شو؟',
      placeholder: 'پوښتنه وکړئ...',
      support: 'د اکاډمي ملاتړ'
    },
    faq: {
      title: 'ډېر پوښتل شوې پوښتنې',
      subtitle: 'زموږ د اکاډمي په اړه عمومي پوښتنو ته ځوابونه ومومئ',
      ctaTitle: 'لا هم پوښتنې لرئ؟',
      ctaText: 'زموږ ملاتړ ټیم د مرستې لپاره دلته دی. هر وخت موږ سره اړیکه ونیسئ!',
      ctaButton: 'موږ سره اړیکه',
      items: [
        {
          question: 'څنګه په کورس کې ثبت نام وکړم؟',
          answer: 'تاسو کولی شئ زموږ ویبسایت له لارې د اصلي پاڼې په "شمولیت" تڼۍ کلیک کولو سره ثبت نام وکړئ. د ثبت نام فورم ډک کړئ او زموږ ټیم به تاسو سره اړیکه ونیسي.'
        },
        {
          question: 'ستاسو د ټولګي وختونه څه دي؟',
          answer: 'موږ د سهار او ماښام ټولګو سره انعطاف منونکی مهال ویش وړاندې کوو. تاسو کولی شئ د ثبت نام پر مهال خپل غوره وخت غوره کړئ.'
        },
        {
          question: 'ایا تاسو انفرادي ناستې وړاندې کوئ؟',
          answer: 'هو! موږ ستاسو د اړتیاو او د زده کړې سرعت مطابق شخصي انفرادي ټولګي وړاندې کوو.'
        },
        {
          question: 'ایا نارینه او ښځینه زده کوونکي په جلا ټولګو کې دي؟',
          answer: 'هو، موږ د اسلامي لارښوونو پیروي کوو او مناسب ښوونکو سره جلا ټولګي ساتو.'
        },
        {
          question: 'که چېرې ما ټولګی له لاسه ورکړ؟',
          answer: 'موږ پوهیږو. له لاسه ورکړل شوي ټولګي معمولاً د ښوونکي سره د جبراني ناستې په مهال ویش کولو سره جبران کیدی شي.'
        },
        {
          question: 'تاسو کومې د تادیې لارې منئ؟',
          answer: 'موږ بانکي لیږد، اعتباري/ډیبیټ کارتونه او ډیجیټل تادیې پلیټفارمونه منو.'
        },
        {
          question: 'ایا تاسو د بشپړیدو وروسته سند ورکوئ؟',
          answer: 'هو! د کورس بریالي بشپړیدو وروسته، موږ سندونه وړاندې کوو.'
        },
        {
          question: 'ایا زه کولی شم په یو وخت کې ډیر کورسونه واخلم؟',
          answer: 'بالکل! ډیر زده کوونکي د خپلې پوهې پراخولو لپاره ډیر کورسونه اخلي.'
        },
        {
          question: 'د آنلاین ټولګو لپاره کومو وسایلو ته اړتیا لرم؟',
          answer: 'تاسو کمپیوټر، ټابلیټ یا سمارټ فون ته د انټرنیټ لاسرسي سره اړتیا لرئ.'
        },
        {
          question: 'زه څنګه د خپل ماشوم پرمختګ تعقیب کولی شم؟',
          answer: 'والدین یو ځانګړي پورټل ته لاسرسی لري چیرته چې کولی شي د خپل ماشوم حاضري، پرمختګ او فعالیت تعقیب کړي.'
        },
        {
          question: 'که زه غواړم د خپل کورس سطحه لوړه کړم؟',
          answer: 'تاسو کولی شئ هر وخت لوړې سطحې ته ارتقا ومومئ. یوازې زموږ ملاتړ ټیم سره اړیکه ونیسئ.'
        },
        {
          question: 'ایا تاسو آزموینې ټولګي وړاندې کوئ؟',
          answer: 'هو! موږ وړیا آزموینې ټولګي وړاندې کوو. د خپل آزموینې درس مهال ویش لپاره موږ سره اړیکه ونیسئ.'
        }
      ]
    },
    social: {
      title: 'موږ تعقیب کړئ',
      connect: 'ټولنیزو رسنیو کې موږ سره وصل شئ'
    },
    footer: {
      explore: 'پلټنه',
      programs: 'برنامې',
      tuition: 'فیسونه',
      enrollment: 'ثبت نام',
      portal: 'پورټل',
      teacherLogin: 'د ښوونکي ننوتل',
      studentLogin: 'د زده کوونکي ننوتل',
      studyGuide: 'د مطالعې لارښود',
      directContact: 'مستقیمه اړیکه',
      whatsappInquiry: 'واتساپ پوښتنه'
    },
    testimonials: {
      title: 'زموږ زده کوونکي څه وايي',
      subtitle: 'زموږ د زده کړې ټولنې رښتیني بریالیتوب کیسې',
      items: [
        {
          name: 'فاطمه احمد',
          role: 'زده کوونکې، 12 کلنه',
          image: 'F',
          rating: 5,
          text: 'ما د وړ ښوونکو څخه ډېر زده کړل. انفرادي ټولګو ما سره مرسته وکړه چې د تجوید قواعد ښه پوه شم. الحمدلله!'
        },
        {
          name: 'محمد حسن',
          role: 'والد',
          image: 'M',
          rating: 5,
          text: 'زما د زوی پرمختګ د پام وړ و. ښوونکي ډېر متعهد او صبور دي. انعطاف منونکی مهال ویش زموږ کورنۍ لپاره مناسب دی.'
        },
        {
          name: 'عایشه خان',
          role: 'زده کوونکې، 9 کلنه',
          image: 'A',
          rating: 5,
          text: 'زه خپله ښوونکې خوښوم! زده کړه اسانه او خوندوره کوي. اوس زه قرآن لوستلی شم!'
        },
        {
          name: 'عمر ابراهیم',
          role: 'کارکوونکی',
          image: 'O',
          rating: 5,
          text: 'د بوخت مهال ویش سره، انعطاف منونکي وختونه عالي وو. انفرادي ناستو ماته اجازه راکړه چې د خپل سرعت سره زده کړم.'
        },
        {
          name: 'لیلا رحمان',
          role: 'والده',
          image: 'L',
          rating: 5,
          text: 'جلا ټولګي زموږ د کورنۍ ارزښتونو سره سمون لري. زما لور آرامه ده او عالي پرمختګ لري.'
        }
      ]
    },
    quran: {
      title: 'د قرآن کریم ملګری',
      surah: 'سوره',
      ayah: 'آیت',
      juz: 'جز',
      page: 'پاڼه',
      search: 'لټون',
      bookmarks: 'نښې',
      translation: 'ترجمه',
      tafsir: 'تفسیر',
      audio: 'غږ',
      wordByWord: 'کلمه په کلمه',
      memorization: 'حفظ',
      readingMode: 'د لوستلو حالت',
      settings: 'امستنې',
      selectSurah: 'سوره غوره کړئ',
      selectTranslation: 'ترجمه غوره کړئ',
      play: 'غږول',
      pause: 'ودرول',
      repeat: 'تکرار',
      previous: 'پخوانی',
      next: 'راتلونکی',
      addBookmark: 'نښه اضافه کړئ',
      addNote: 'یادداشت اضافه کړئ',
      daily: 'ورځنی آیت',
      topics: 'موضوعات',
      meccan: 'مکي',
      medinan: 'مدني',
      verses: 'آیتونه',
      loading: 'بار کیږي...',
      noResults: 'پایلې ونه موندل شوې',
      reciter: 'قاري',
      transliteration: 'آوا لیکنه',
      root: 'ریښه',
      meaning: 'مانا',
      grammar: 'ګرامر'
    },
    studentProgress: {
      title: 'ستاسو پرمختګ',
      subtitle: 'د قرآن د زده کړې خپل سفر تعقیب کړئ',
      stats: {
        overall: 'ټولیز پرمختګ',
        lessons: 'درسونه',
        lessonsDesc: 'بشپړ شوي',
        quizzes: 'بریالي ازموینې',
        avg: 'اوسط',
        attendance: 'حاضري',
        attendanceDesc: 'دا میاشت'
      },
      courseProgress: 'د کورس پرمختګ',
      learningDistribution: 'د زده کړې توزیع',
      categories: ['ویډیوګانې', 'تمرین', 'لوستل', 'ازموینې'],
      attendanceTrend: 'د حاضرۍ رجحان',
      quizPerformance: 'د ازموینو فعالیت',
      quizzes: ['ازموینه 1', 'ازموینه 2', 'ازموینه 3', 'ازموینه 4', 'ازموینه 5'],
      courses: ['تجوید', 'حفظ قرآن', 'اسلامي مطالعات'],
      recentActivity: 'وروستۍ فعالیت',
      today: 'نن',
      yesterday: 'پرون'
    },
    adminAnalytics: {
      title: 'د سیستم تحلیل',
      subtitle: 'د اکاډمي فعالیت جامع کتنه',
      thisMonth: 'دا میاشت',
      stats: {
        students: 'ټول زده کوونکي',
        courses: 'فعال کورسونه',
        revenue: 'میاشتنۍ عاید',
        completion: 'د بشپړیدو نرخ'
      },
      revenueTrend: 'د عاید رجحان',
      studentGrowth: 'د زده کوونکو د ثبت نام وده',
      topCourses: 'غوره کورسونه',
      distribution: 'د سطحې مطابق د زده کوونکو ویش',
      retention: 'ګروهي ساتنه',
      teacherPerformance: 'د درجې مطابق غوره ښوونکي',
      levels: ['پیل کوونکی', 'منځنی', 'پرمختللی'],
      teachers: ['استاذه فاطمه', 'شیخ محمد', 'استاذه عایشه', 'شیخ عمر', 'استاذه لیلا'],
      courses: ['تجوید', 'حفظ', 'اسلامي مطالعات', 'عربي نحو', 'تفسیر'],
      summary: 'د سیستم لنډیز',
      activeStudents: 'فعال زده کوونکي',
      totalTeachers: 'فعال ښوونکي',
      totalEnrollments: 'ټول ثبت نامونه',
      totalRevenue: 'ټول عاید',
      enrolled: 'د ټولټال',
      available: 'شتون لري',
      perStudent: 'د هر زده کوونکي لپاره',
      allTime: 'ټول وختونه',
      students: 'زده کوونکي'
    },
    socialMedia: {
      title: 'موږ تعقیب کړئ',
      subtitle: 'ټولنیزو رسنیو کې موږ سره وصل شئ',
      facebook: 'فیسبوک',
      twitter: 'ټویټر',
      instagram: 'انسټاګرام',
      linkedin: 'لینکډین',
      youtube: 'یوټیوب',
      whatsapp: 'واتساپ',
      telegram: 'ټلیګرام',
      tiktok: 'ټیک ټاک',
      visitPage: 'پاڼه وګورئ'
    },
    exploreCategories: {
      quran: 'قرآن او تجوید',
      islamicStudies: 'اسلامي مطالعات',
      languages: 'ژبې',
      ai: 'مصنوعي هوښیارتیا',
      it: 'معلوماتي ټکنالوجي',
      science: 'ساینس',
      generalKnowledge: 'عمومي پوهه',
      lifeSkills: 'د ژوند مهارتونه',
      digitalSkills: 'ډیجیټل مهارتونه'
    },
    studentJourney: {
      label: 'د زده کوونکي سفر',
      title: 'د لومړیو تورو څخه تر سند پورې روښانه نقشه',
      subtitle: 'والدین او زده کوونکي تل پوهیږي چې وروسته څه راځي، پرمختګ څنګه اندازه کیږي او سند کله ورکول کیږي.',
      steps: ['د پیل بنسټونه', 'د تجوید تسلط', 'د حفظ لاره', 'تفسیر او مانا', 'سند'],
      levels: [
        { label: 'پیل کوونکی', detail: 'عربي توري، د لوستلو روانۍ' },
        { label: 'منځنی', detail: 'د تجوید قواعد او تمرین' },
        { label: 'پرمختللی', detail: 'حفظ + تفسیري مهارتونه' }
      ],
      progressTracking: 'د پرمختګ تعقیب',
      liveDashboard: 'د والدینو او زده کوونکو لپاره ژوندۍ ډشبورډ',
      liveDashboardDesc: 'حاضري، د ښوونکي نظریات، د حفظ لویې لاسته راوړنې او میاشتنۍ راپورونه په یو ځای کې.',
      certification: 'سند',
      earnCertificates: 'تایید شوي سندونه ترلاسه کړئ',
      earnCertificatesDesc: 'زده کوونکي په مهمو پړاونو او وروستي بشپړیدو کې سندونه ترلاسه کوي.',
      startJourney: 'سفر پیل کړئ'
    },
    noorani: {
      badge: 'نوی کورس',
      title1: 'قرآن او لمونځ زده کړئ',
      title2: 'د نورانی قاعدې سره',
      description: 'د 3 برخو جامع کورس د 19 تعاملي درسونو، ازموینو او لوبو سره. د پیل کوونکو او پرمختللو لپاره مناسب.',
      feature1Title: 'عربي الفبا او تجوید (12 درسونه)',
      feature1Desc: 'عربي توري، قرآني قواعد او سمه تلاوت زده کړئ',
      feature2Title: 'ورځنی لمونځ تمرین (7 درسونه)',
      feature2Desc: 'د ویډیو نمایشونو او ګام په ګام لارښوونو سره بشپړ لارښود',
      feature3Title: 'د پرمختګ تعقیب او سندونه',
      feature3Desc: 'نښې ترلاسه کړئ، سلسلې وساتئ او د بشپړیدو وروسته سند ترلاسه کړئ',
      exploreCourse: 'کورس وپلټئ',
      lessonsCount: '19 درسونه',
      completeEducation: 'بشپړ اسلامي تعلیم',
      sections: 'برخې',
      lessons: 'درسونه',
      free: 'وړیا'
    },
    footerExtra: {
      aboutUs: 'زموږ په اړه',
      aboutDesc: 'د ټولو عمرونو لپاره د قرآني تعلیم برتري',
      quickLinks: 'ګړندي لینکونه',
      parentDashboard: 'د والدینو ډشبورډ',
      quranLink: 'قرآن',
      contactUs: 'موږ سره اړیکه',
      allRights: 'ټول حقوق خوندي دي.'
    },
    charity: {
      title: 'د محمدي بنسټ',
      subtitle: 'د نړیوالو اسلامي تعلیم ملاتړ',
      mission: 'زموږ ماموریت',
      missionText: 'په نړۍ کې محرومو ټولنو ته د قرآني تعلیم او اسلامي پوهې رسول.',
      impact: 'زموږ اغیزه',
      students: 'ملاتړ شوي زده کوونکي',
      teachers: 'روزل شوي ښوونکي',
      communities: 'رسیدل شوې ټولنې',
      scholarships: 'ورکړل شوې بورسونه',
      donate: 'مرسته وکړئ',
      donateNow: 'اوس مرسته وکړئ',
      programs: 'زموږ برنامې',
      scholarship: 'د بورس برنامه',
      scholarshipDesc: 'هغو زده کوونکو ته مالي مرسته چې د تعلیم لګښت نشي ورکولی',
      community: 'ټولنیزه فعالیت',
      communityDesc: 'محرومو ټولنو کې وړیا قرآني ټولګي',
      teacher: 'د ښوونکو روزنه',
      teacherDesc: 'د اسلامي ښوونکو لپاره مسلکي پراختیا برنامې',
      research: 'څیړنه او پراختیا',
      researchDesc: 'نوښتګرانه اسلامي تعلیمي میتودونه جوړول',
      ways: 'د مرستې لارې',
      bank: 'بانکي لیږد',
      card: 'اعتباري / ډیبیټ کارت',
      mobile: 'موبایل تادیه',
      crypto: 'کریپتو اسعار',
      zakat: 'د زکات وړ',
      tax: 'له مالیې معاف',
      monthly: 'میاشتنی مرسته کوونکی شئ',
      monthlyDesc: 'د دوامداره اغیزې لپاره منظمه مرسته',
      contactDonor: 'د مرستې لپاره اړیکه',
      email: 'بریښنالیک',
      phone: 'تلیفون',
      thank: 'مننه',
      thankYouMsg: 'ستاسو سخاوتمنده مرسته د خلکو په ژوند کې رښتینی توپیر رامنځته کوي'
    }
  }
};
