export const ACADEMY_NAME = 'Muhammadi Online Academy';
export const PHONE_NUMBER = '+1 (555) 123-4567';

export const TRANSLATIONS = {
  en: {
    dir: 'ltr',
    name: 'Muhammadi Online Academy',
    shortName: 'Muhammadi Academy',
    tagline: 'Connecting Hearts with Knowledge for Every Learner',
    brighterLearning: 'Brighter Learning',
    heroSub: 'At Muhammadi Online Academy, we connect hearts with foundational knowledge across faith, character, and modern skills. We believe learning builds values, critical thinking, and practical capability.',
    mission: 'Guided by faith and excellence, we deliver knowledge that shapes character, builds skills, and serves communities.',
    nav: { courses: 'Courses', pricing: 'Pricing', admission: 'Admission', enroll: 'Enroll Now' },
    courses: {
      title: 'What We Offer',
      subtitle: 'All classes are one-on-one, interactive, and tailored to student level',
      c1: 'Quran Reading with Tajweed',
      c1Desc: 'Learn proper Quran reading with complete tajweed rules.',
      c2: 'Quran Memorization with Review',
      c2Desc: 'Solid memorization with clear methodology and regular review for retention.',
      c3: 'Quran with Tafsir and Translation',
      c3Desc: 'Understand verse meanings, purposes, and ponder Allah\'s word.',
      c4: 'Noor Ania Foundation',
      c4Desc: 'Strong foundation for learning correct reading from zero.',
      c5: 'Arabic for the Quran',
      c5Desc: 'Learn Arabic to understand the Quran and speak with confidence.',
      c6: 'Islamic Studies and Daily Supplications',
      c6Desc: 'Teaching Islamic fundamentals, prayer, remembrances, and daily supplications.'
    },
    pricing: {
      title: 'Tuition Packages',
      subtitle: 'Simple and affordable monthly rates',
      basic: 'Basic Package',
      standard: 'Standard Package',
      premium: 'Premium Package',
      month: 'Month',
      popular: 'Most Popular',
      choose: 'Choose Package'
    },
    form: {
      notice: 'Classes are conducted separately with male and female teachers according to Islamic guidelines.',
      gender: 'Student Gender',
      male: 'Male',
      female: 'Female',
      preferredTeacher: 'Preferred Teacher Gender',
      preferredMale: 'Male Teacher',
      preferredFemale: 'Female Teacher',
      noPreference: 'No Preference',
      studentAge: 'Student Age',
      country: 'Country',
      timezone: 'Time Zone',
      quranLevel: 'Quran Level',
      beginner: 'Beginner (None)',
      canRead: 'Can Read',
      tajweed: 'Tajweed',
      hifz: 'Memorization',
      availability: 'Time Availability',
      availableDays: 'Available Days',
      preferredTime: 'Preferred Time',
      parentSection: 'Parent Information',
      parentName: 'Parent Name',
      parentEmail: 'Parent Email',
      parentPhone: 'Parent Phone',
      islamicConsent: 'Islamic Consent',
      consent1: 'I agree that classes are conducted with gender separation according to Islamic guidelines (male teacher for boys, female teacher for girls).',
      consent2: 'I agree that parents can observe classes and there is no private chat between teacher and student.',
      consent3: 'I accept and respect Mohammadi Academy policies.'
    },
    teacherForm: {
      title: 'Teacher Employment Request',
      notice: 'Teachers are appointed after verification of correct recitation and Islamic character.',
      fullName: 'Full Name',
      gender: 'Gender',
      email: 'Email',
      phone: 'Phone',
      country: 'Country',
      qualifications: 'Qualifications',
      tajweedDetails: 'Tajweed / Ijazah Details',
      experienceYears: 'Years of Experience',
      languagesTaught: 'Languages You Teach',
      teachingPreferences: 'Teaching Preferences',
      teachKids: 'Children',
      teachAdults: 'Adults',
      teachBoth: 'Both',
      availableDays: 'Available Days',
      availableTimes: 'Available Times',
      islamicAgreement: 'Islamic Agreement',
      consentManners: 'I will follow Quranic ethics and manners in class.',
      consentNoChat: 'I will not engage in private chat with students and all communication will be through the academy system.',
      consentPolicy: 'I accept Mohammadi Academy policies.',
      submit: 'Submit Request',
      success: 'JazakAllah! Request received.',
      successSub: 'Your request is under review. We will contact you soon.'
    },
    common: {
      login: 'Login',
      register: 'Register',
      enrollNow: 'Enroll Now',
      home: 'Home',
      about: 'About Us',
      contact: 'Contact Us',
      backToHome: 'Back to Home',
      ourCourses: 'Our Courses',
      comprehensiveEducation: 'Comprehensive Islamic education from qualified teachers',
      filterBy: 'Filter By',
      allCourses: 'All Courses',
      allLevels: 'All Levels',
      beginner: 'Beginner',
      intermediate: 'Intermediate',
      advanced: 'Advanced',
      viewDetails: 'View Details'
    },
    articles: {
      title: 'Islamic Articles and Reflections',
      heading: 'Discover Wisdom and Guidance',
      subtitle: 'Authentic Islamic content connecting real-life events and daily struggles with the eternal wisdom of the Quran and Sunnah.',
      readArticle: 'Read Article',
      readTime: 'minute read',
      category: 'Knowledge and Learning',
      audience: 'Mixed Audience',
      joinCommunity: 'Join Our Learning Community',
      joinText: 'Enroll in our courses to deepen your understanding of Islam and connect with seekers of knowledge worldwide.',
      backToArticles: 'Back to Articles'
    },
    aboutUs: {
      title: 'About Us',
      subtitle: 'Empowering Muslims worldwide to engage with the Quran through quality, accessible online education with dedicated teachers.',
      ourMission: 'Our Mission',
      missionText: 'Deliver authentic Quranic education that transforms lives by building strong foundations in Faith, Morals, and Knowledge.',
      ourVision: 'Our Vision',
      visionText: 'A world where every Muslim has access to quality Islamic education, nurturing a generation committed to the Quran and Sunnah.',
      whyChooseUs: 'Why Choose Us',
      qualifiedTeachers: 'Qualified Teachers',
      qualifiedTeachersDesc: 'Certified instructors with Ijazah in Quran recitation and years of teaching experience.',
      flexibleSchedule: 'Flexible Schedule',
      flexibleScheduleDesc: 'Learn at your own pace with class times that fit your lifestyle.',
      oneOnOne: 'One-on-One Classes',
      oneOnOneDesc: 'Personal attention with individual sessions tailored to your learning needs.',
      islamicEnvironment: 'Islamic Environment',
      islamicEnvironmentDesc: 'Gender-separated classes following Islamic guidelines with parental supervision.',
      affordableFees: 'Affordable Fees',
      affordableFeesDesc: 'Quality education at reasonable prices with flexible payment plans.',
      provenResults: 'Proven Results',
      provenResultsDesc: 'Thousands of students have successfully completed their Quranic journey with us.'
    },
    dashboard: {
      admin: {
        title: 'Admin Dashboard',
        dashboard: 'Dashboard',
        courses: 'Courses',
        createCourse: 'Create Course',
        editCourses: 'Edit Courses',
        lessonsManager: 'Lessons Manager',
        mediaLibrary: 'Media Library',
        students: 'Students',
        addStudent: 'Add Student',
        allStudents: 'All Students',
        progressRecords: 'Progress Records',
        admissions: 'Admissions',
        teachers: 'Teachers',
        addTeacher: 'Add Teacher',
        teacherList: 'Teacher List',
        schedule: 'Schedule',
        academic: 'Academic',
        attendance: 'Attendance',
        homework: 'Homework',
        exams: 'Exams and Quizzes',
        results: 'Results',
        finance: 'Finance',
        feeRecords: 'Fee Records',
        feePlans: 'Fee Plans',
        invoices: 'Invoices',
        payments: 'Payments',
        reports: 'Reports',
        communication: 'Communication',
        announcements: 'Announcements',
        messages: 'Messages',
        website: 'Website Management',
        homePage: 'Home Page',
        pricingPackages: 'Pricing Packages',
        coursesPage: 'Courses Page',
        mediaBanners: 'Media and Banners',
        settings: 'Settings',
        adminManagement: 'Admin Management',
        seedDatabase: 'Seed Database',
        logout: 'Logout'
      },
      teacher: {
        title: 'Teacher Portal',
        dashboard: 'Dashboard',
        myStudents: 'My Students',
        lessons: 'Lessons',
        attendance: 'Attendance',
        announcements: 'Announcements',
        logout: 'Logout'
      },
      student: {
        title: 'Student Portal',
        dashboard: 'Dashboard',
        myProgress: 'My Progress',
        myProfile: 'My Profile',
        attendance: 'Attendance',
        fees: 'Fees',
        announcements: 'Announcements',
        logout: 'Logout'
      },
      common: {
        welcome: 'Welcome',
        profile: 'Profile',
        notifications: 'Notifications',
        search: 'Search',
        filter: 'Filter',
        export: 'Export',
        import: 'Import',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        view: 'View',
        add: 'Add',
        submit: 'Submit',
        close: 'Close',
        confirm: 'Confirm',
        loading: 'Loading...',
        noData: 'No Data',
        error: 'Error',
        success: 'Success',
        warning: 'Warning',
        info: 'Information'
      }
    },
    chat: {
      greeting: 'Assalamu Alaikum! Welcome to Mohammadi Academy. How can we help you?',
      placeholder: 'Ask a question...',
      support: 'Academy Support'
    },
    faq: {
      title: 'Frequently Asked Questions',
      subtitle: 'Find answers to common questions about our academy',
      ctaTitle: 'Have More Questions?',
      ctaText: 'Our support team is here to help. Contact us anytime!',
      ctaButton: 'Contact Us',
      items: [
        { question: 'How do I enroll in a course?', answer: 'You can register through our website by clicking the Admission button and filling out the registration form. Our team will contact you to confirm your enrollment.' },
        { question: 'What are the class times?', answer: 'We offer flexible scheduling with morning and evening classes. You can choose your preferred time.' },
        { question: 'Do you offer one-on-one sessions?', answer: 'Yes! We offer customized one-on-one sessions tailored to meet your specific learning needs.' },
        { question: 'Are male and female students in separate classes?', answer: 'Yes, we follow Islamic teachings and have separate classes for male and female students.' },
        { question: 'What if I miss a class?', answer: 'We understand life happens. Classes can usually be rescheduled or compensated with additional sessions.' },
        { question: 'What payment methods do you accept?', answer: 'We accept bank transfers, credit cards, and digital wallets. Flexible payment plans are available.' },
        { question: 'Do you provide certificates upon completion?', answer: 'Yes! We provide recognized certificates upon successful course completion.' },
        { question: 'Can I take multiple courses at the same time?', answer: 'Absolutely! We can help you create a personalized learning schedule that works for you.' },
        { question: 'What equipment do I need?', answer: 'You need a computer or smartphone with internet connection. A quiet space for focus is helpful.' },
        { question: 'How can parents monitor their child\'s progress?', answer: 'Parents have access to a private portal to track their child\'s attendance and progress.' },
        { question: 'Can I upgrade to a higher level?', answer: 'Of course! You can upgrade to a higher level anytime. Just contact us.' },
        { question: 'Do you offer free trial lessons?', answer: 'Yes! We offer free trial lessons to experience our teaching style before committing.' }
      ]
    },
    social: {
      title: 'Follow Us',
      connect: 'Connect with us on social media'
    },
    footer: {
      explore: 'Explore',
      programs: 'Programs',
      tuition: 'Tuition',
      enrollment: 'Enrollment',
      portal: 'Portal',
      teacherLogin: 'Teacher Login',
      studentLogin: 'Student Login',
      studyGuide: 'Study Guide',
      directContact: 'Direct Contact',
      whatsappInquiry: 'WhatsApp Inquiry'
    },
    testimonials: {
      title: 'What Our Students Say',
      subtitle: 'Real success stories from our learning community',
      items: [
        {
          name: 'Fatima Ahmed',
          role: 'Student, 12 years old',
          image: 'F',
          rating: 5,
          text: 'I learned a lot from the qualified teachers. One-on-one lessons help me understand tajweed rules better. Alhamdulillah, I completed my first Quran recitation with proper tajweed!'
        },
        {
          name: 'Muhammad Hassan',
          role: 'Parent',
          image: 'M',
          rating: 5,
          text: 'My son\'s progress has been excellent. The teachers are very dedicated and patient. The flexible schedule works perfectly for our family. I highly recommend for anyone seeking quality Quranic education.'
        },
        {
          name: 'Aisha Khan',
          role: 'Student, 9 years old',
          image: 'A',
          rating: 5,
          text: 'I love my Quran class! My teacher is very kind and makes learning fun and easy. Now I can read the Quran and understand what I\'m reading. The class time works perfectly with my school schedule!'
        },
        {
          name: 'Omar Ibrahim',
          role: 'Working Professional',
          image: 'O',
          rating: 5,
          text: 'As a busy person, the flexible schedule was a game-changer. One-on-one lessons let me learn at my own pace. Best investment in my Islamic education!'
        },
        {
          name: 'Leila Rahman',
          role: 'Parent',
          image: 'L',
          rating: 5,
          text: 'The gender-separated classes align with our family values. My daughter feels comfortable and is making excellent progress. Teachers regularly communicate about her advancement.'
        }
      ]
    },
    teachers: {
      title: 'Our Qualified Teachers',
      subtitle: 'Meet our dedicated and certified Quran teachers committed to your Islamic education',
      contactButton: 'Contact Teacher',
      ctaTitle: 'Ready to Get Started?',
      ctaText: 'Connect with one of our expert teachers and begin your Quranic journey today',
      items: [
        {
          name: 'Teacher Fatima Al-Rasheed',
          specialization: 'Tajweed Specialist',
          qualifications: 'Certified Tajweed Teacher with Ijazah from Al-Azhar University',
          experience: '8 years of teaching experience',
          studentsCount: '150+ students taught',
          rating: 4.9,
          bio: 'Specializes in teaching tajweed rules with practical application. Known for patience and clear explanations.',
          image: 'F',
          specialities: ['Tajweed', 'Quranic Arabic', 'Phonetics']
        },
        {
          name: 'Sheikh Muhammad Al-Zahra',
          specialization: 'Hafiz and Quran Scholar',
          qualifications: 'Hafiz with 20+ years experience, Islamic Studies degree from Medina University',
          experience: '15 years teaching Quran memorization',
          studentsCount: '200+ students, 45 hafiz graduates',
          rating: 5.0,
          bio: 'Expert in memorization techniques and Quranic sciences. Helped many students complete strong memorization.',
          image: 'M',
          specialities: ['Memorization', 'Tafsir', 'Quranic Sciences']
        },
        {
          name: 'Teacher Aisha Karim',
          specialization: 'Children\'s Quran Education',
          qualifications: 'Certified Islamic Teacher with specialization in early childhood education',
          experience: '10 years teaching children ages 4-12',
          studentsCount: '180+ young learners',
          rating: 4.95,
          bio: 'Makes Quran learning fun and engaging for children. Uses interactive methods and games to enhance learning.',
          image: 'A',
          specialities: ['Children Education', 'Noor Ania', 'Beginner Tajweed']
        },
        {
          name: 'Sheikh Omar Abdullah',
          specialization: 'Advanced Quranic Studies',
          qualifications: 'Master\'s degree in Islamic Studies, Quran Tafsir specialist',
          experience: '12 years teaching advanced levels',
          studentsCount: '120+ advanced students',
          rating: 4.92,
          bio: 'Focuses on Tafsir, Quranic sciences and understanding deeper meanings of the Quran.',
          image: 'O',
          specialities: ['Tafsir', 'Arabic Grammar', 'Islamic Jurisprudence']
        },
        {
          name: 'Teacher Layla Ibrahim',
          specialization: 'One-on-One Sessions',
          qualifications: 'Certified Quran Teacher with specialized training in personalized instruction',
          experience: '9 years of one-on-one teaching',
          studentsCount: '140+ private students',
          rating: 4.98,
          bio: 'Expert in creating customized learning paths for adult learners. Flexible, patient and results-oriented.',
          image: 'L',
          specialities: ['Adult Learning', 'Quranic Arabic', 'Fluency']
        },
        {
          name: 'Sheikh Hassan Ali',
          specialization: 'Islamic Fundamentals',
          qualifications: 'Bachelor\'s in Islamic Education, certified in multiple Quranic recitation styles',
          experience: '11 years teaching fundamentals',
          studentsCount: '170+ beginner learners',
          rating: 4.91,
          bio: 'Expert in building strong Quranic foundations. Excellent with absolute beginners and struggling learners.',
          image: 'H',
          specialities: ['Noor Ania', 'Basic Tajweed', 'Arabic for Beginners']
        }
      ]
    },
    quran: {
      title: 'Quran Companion',
      surah: 'Surah',
      ayah: 'Ayah',
      juz: 'Juz',
      page: 'Page',
      search: 'Search',
      bookmarks: 'Bookmarks',
      translation: 'Translation',
      tafsir: 'Tafsir',
      audio: 'Audio',
      wordByWord: 'Word by Word',
      memorization: 'Memorization',
      readingMode: 'Reading Mode',
      settings: 'Settings',
      selectSurah: 'Select Surah',
      selectTranslation: 'Select Translation',
      play: 'Play',
      pause: 'Pause',
      repeat: 'Repeat',
      previous: 'Previous',
      next: 'Next',
      addBookmark: 'Add Bookmark',
      addNote: 'Add Note',
      daily: 'Verse of the Day',
      topics: 'Topics',
      meccan: 'Meccan',
      medinan: 'Medinan',
      verses: 'Verses',
      loading: 'Loading...',
      noResults: 'No results found',
      reciter: 'Reciter',
      transliteration: 'Transliteration',
      root: 'Root',
      meaning: 'Meaning',
      grammar: 'Grammar'
    },
    studentProgress: {
      title: 'Your Progress',
      subtitle: 'Track your Quranic learning journey',
      stats: {
        overall: 'Overall Progress',
        lessons: 'Lessons',
        lessonsDesc: 'Completed',
        quizzes: 'Quizzes Passed',
        avg: 'Average',
        attendance: 'Attendance',
        attendanceDesc: 'This Month'
      },
      courseProgress: 'Course Progress',
      learningDistribution: 'Learning Distribution',
      categories: ['Videos', 'Practice', 'Reading', 'Quizzes'],
      attendanceTrend: 'Attendance Trend',
      quizPerformance: 'Quiz Performance',
      quizzes: ['Quiz 1', 'Quiz 2', 'Quiz 3', 'Quiz 4', 'Quiz 5'],
      courses: ['Tajweed', 'Quran Memorization', 'Islamic Studies'],
      recentActivity: 'Recent Activity',
      today: 'Today',
      yesterday: 'Yesterday'
    },
    adminAnalytics: {
      title: 'System Analytics',
      subtitle: 'Comprehensive overview of academy performance',
      thisMonth: 'This Month',
      stats: {
        students: 'Total Students',
        courses: 'Active Courses',
        revenue: 'Monthly Revenue',
        completion: 'Completion Rate'
      },
      revenueTrend: 'Revenue Trend',
      studentGrowth: 'Enrollment Growth',
      topCourses: 'Top Courses',
      distribution: 'Student Distribution by Level',
      retention: 'Student Retention',
      teacherPerformance: 'Top Teachers by Rating',
      levels: ['Beginner', 'Intermediate', 'Advanced'],
      teachers: ['Teacher Fatima', 'Sheikh Muhammad', 'Teacher Aisha', 'Sheikh Omar', 'Teacher Layla'],
      courses: ['Tajweed', 'Memorization', 'Islamic Studies', 'Arabic Grammar', 'Tafsir'],
      summary: 'System Summary',
      activeStudents: 'Active Students',
      totalTeachers: 'Active Teachers',
      totalEnrollments: 'Total Enrollments',
      totalRevenue: 'Total Revenue',
      enrolled: 'of Total',
      available: 'Available',
      perStudent: 'Per Student',
      allTime: 'All Time',
      students: 'Students'
    }
  }
};



